# Generated by Django 5.0.4 on 2024-04-17 03:43

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import djmoney.models.fields
import incredible_data.business.models.business_accounting_models
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_created_by_alter_customer_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('stimate', 'Estimate'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='draft', max_length=50, verbose_name='status')),
                ('terms', models.TextField(blank=True, verbose_name='terms')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='subtotal')),
                ('grand_total_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('grand_total', djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='grand total')),
                ('due_date', models.DateField(default=incredible_data.business.models.business_accounting_models.thirty_days, verbose_name='due date')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='number')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='customer')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='rank')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=5, default=1, max_digits=15, verbose_name='quantity')),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='unit price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.invoice', verbose_name='invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(editable=False, max_length=10, verbose_name='order number')),
                ('expected_date', models.DateField(default=incredible_data.business.models.business_accounting_models.fourteen_days, verbose_name='expected completion date')),
                ('notes', models.TextField(blank=True, verbose_name='order notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='customer')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
