# Generated by Django 5.0.4 on 2024-04-18 07:19

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['customer', 'number']),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='number'),
        ),
    ]
