# Generated by Django 5.0.6 on 2024-06-19 04:21

import django.db.models.deletion
import django_rubble.fields.auto_fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_order_slug_alter_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=django_rubble.fields.auto_fields.AutoCreatedByField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modified_by',
            field=django_rubble.fields.auto_fields.AutoModifiedByField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=model_utils.fields.StatusField(choices=[('draft', 'Draft'), ('stimate', 'Estimate'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
