# Generated by Django 5.2.2 on 2025-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_invoice_created_by_alter_invoice_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='rank'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'rank'), name='unique_line_rank'),
        ),
    ]
