# Generated by Django 5.2.2 on 2025-06-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_invoiceline_rank_invoiceline_unique_line_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['rank']},
        ),
    ]
