# Generated by Django 5.2.2 on 2025-06-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_invoiceline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['number']},
        ),
    ]
