"""This type stub file was generated by pyright."""  # noqa: PYI021

# pyright: reportMissingTypeArgument=false, reportUnknownMemberType=false
from collections.abc import Callable, Generator, Iterable, Sequence
from typing import SupportsIndex, TypeAlias

from django.db import models
from django.db.models import CharField, DateTimeField, SlugField
from django.utils.functional import _StrOrPromise  # pyright: ignore[reportPrivateUsage]

"""
Django Extensions additional model fields

Some fields might require additional dependencies to be installed.
"""
HAS_UUID: bool
HAS_SHORT_UUID: bool
MAX_UNIQUE_QUERY_ATTEMPTS: int = 100

_ArgKwarg: TypeAlias = int | bool | str | None

class UniqueFieldMixin:
    def check_is_bool(self, attrname: str) -> None: ...
    def get_queryset(
        self, model_cls: type[models.Model], slug_field: object
    ) -> models.QuerySet: ...
    def find_unique(
        self,
        model_instance: models.Model,
        field: object,
        iterator: Iterable,
        *args: _ArgKwarg,
    ): ...

class AutoSlugField(UniqueFieldMixin, SlugField):
    slugify_function: Callable[..., _StrOrPromise]
    separator: str = "-"
    overwrite: bool = False
    overwrite_on_add: bool = True
    allow_duplicates: bool = False
    max_unique_query_attempts: int

    def __init__(
        self,
        *args: _ArgKwarg,
        blank: bool = True,
        editable: bool = False,
        populate_from: str | Sequence[str] | Callable,
        slugify_function: Callable[..., _StrOrPromise] = ...,
        **kwargs: _ArgKwarg,
    ) -> None: ...
    @staticmethod
    def slugify_func(content, slugify_function):  # -> Literal['']:
        ...
    def slug_generator(
        self, original_slug: str, start: SupportsIndex
    ) -> Generator[str, None, None]: ...
    def create_slug(self, model_instance: models.Model, add: bool) -> str: ...
    def get_slug_fields(
        self, model_instance: models.Model, lookup_value
    ):  # -> str | Any:
        ...
    def pre_save(self, model_instance, add):  # -> Any | str:
        ...
    def get_internal_type(self):  # -> Literal['SlugField']:
        ...
    def deconstruct(self):  # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...

class RandomCharField(UniqueFieldMixin, CharField):
    """
    RandomCharField

    By default, sets editable=False, blank=True, unique=False.

    Required arguments:

    length
        Specifies the length of the field

    Optional arguments:

    unique
        If set to True, duplicate entries are not allowed (default: False)

    lowercase
        If set to True, lowercase the alpha characters (default: False)

    uppercase
        If set to True, uppercase the alpha characters (default: False)

    include_alpha
        If set to True, include alpha characters (default: True)

    include_digits
        If set to True, include digit characters (default: True)

    include_punctuation
        If set to True, include punctuation characters (default: False)

    keep_default
        If set to True, keeps the default initialization value (default: False)
    """
    def __init__(self, *args, **kwargs) -> None: ...
    def random_char_generator(self, chars):  # -> Generator[str, Any, Never]:
        ...
    def in_unique_together(self, model_instance):  # -> bool:
        ...
    def pre_save(self, model_instance, add):  # -> Any | str:
        ...
    def internal_type(self):  # -> Literal['CharField']:
        ...
    def deconstruct(self):  # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...

class CreationDateTimeField(DateTimeField):
    """
    CreationDateTimeField

    By default, sets editable=False, blank=True, auto_now_add=True
    """
    def __init__(self, *args, **kwargs) -> None: ...
    def get_internal_type(self):  # -> Literal['DateTimeField']:
        ...
    def deconstruct(self):  # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...

class ModificationDateTimeField(CreationDateTimeField):
    """
    ModificationDateTimeField

    By default, sets editable=False, blank=True, auto_now=True

    Sets value to now every time the object is saved.
    """
    def __init__(self, *args, **kwargs) -> None: ...
    def get_internal_type(self):  # -> Literal['DateTimeField']:
        ...
    def deconstruct(self):  # -> tuple[str, str, Sequence[Any], dict[str, Any]]:
        ...
    def pre_save(self, model_instance, add):  # -> Any:
        ...

class UUIDVersionError(Exception): ...

class UUIDFieldMixin:
    """
    UUIDFieldMixin

    By default uses UUID version 4 (randomly generated UUID).

    The field support all uuid versions which are natively supported by the uuid python module, except version 2.
    For more information see: https://docs.python.org/lib/module-uuid.html
    """

    DEFAULT_MAX_LENGTH = ...
    def __init__(
        self,
        verbose_name=...,
        name=...,
        auto=...,
        version=...,
        node=...,
        clock_seq=...,
        namespace=...,
        uuid_name=...,
        *args,
        **kwargs,
    ) -> None: ...
    def create_uuid(self):  # -> UUID:
        ...
    def pre_save(self, model_instance, add):  # -> str:
        ...
    def formfield(self, **kwargs):  # -> None:
        ...
    def deconstruct(self):  # -> tuple[Any, Any, Any, Any]:
        ...

class ShortUUIDField(UUIDFieldMixin, CharField):
    """
    ShortUUIDFied

    Generates concise (22 characters instead of 36), unambiguous, URL-safe UUIDs.

    Based on `shortuuid`: https://github.com/stochastic-technologies/shortuuid
    """

    DEFAULT_MAX_LENGTH = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def create_uuid(self):  # -> str:
        ...
