DEFAULTS = ...
DEPRECATED_SETTINGS = ...

def is_callable(value):  # -> TypeIs[Callable[..., object]] | bool:
    ...

class Settings:
    def __getattr__(self, name):  # -> Any | bool | str | dict[str, str] | None:
        ...
    def get_setting(self, setting):  # -> Any | bool | str | dict[str, str] | None:
        ...
    def change_setting(self, setting, value, enter, **kwargs):  # -> None:
        ...

settings = ...
