from enum import Enum
from typing import Any

from django.db.models.fields import Field
from django.db.models.fields.reverse_related import ForeignObjectRel
from django_filters.filters import Filter

def remote_queryset(field): ...

class UnknownFieldBehavior(Enum):
    RAISE = ...
    WARN = ...
    IGNORE = ...

class FilterSetOptions:
    def __init__(self, options=...) -> None: ...

class FilterSetMetaclass(type):
    def __new__(cls, name, bases, attrs):  # -> Self:
        ...
    @classmethod
    def get_declared_filters(cls, bases, attrs):  # -> OrderedDict[Any, Any]:
        ...

FILTER_FOR_DBFIELD_DEFAULTS: dict[type[Field[Any]], Filter] = ...

class BaseFilterSet:
    FILTER_DEFAULTS: dict[type[ForeignObjectRel], dict[str, type[Filter]]] = ...  # pyright: ignore[reportAny]
    def __init__(self, data=..., queryset=..., *, request=..., prefix=...) -> None: ...
    def is_valid(self):  # -> Literal[False]:
        ...
    @property
    def errors(self): ...
    def filter_queryset(self, queryset):  # -> QuerySet[Any]:
        ...
    @property
    def qs(self):  # -> QuerySet[Any]:
        ...
    def get_form_class(self):  # -> type[_]:
        ...
    @property
    def form(self):  # -> _:
        ...
    @classmethod
    def get_fields(
        cls,
    ):  # -> OrderedDict[Any, list[Any | bool | str | dict[str, str] | None]]:
        ...
    @classmethod
    def get_filter_name(cls, field_name, lookup_expr):  # -> str:
        ...
    @classmethod
    def get_filters(cls):  # -> OrderedDict[Any, Any]:
        ...
    @classmethod
    def handle_unrecognized_field(cls, field_name, message):  # -> None:
        ...
    @classmethod
    def filter_for_field(
        cls, field, field_name, lookup_expr=...
    ):  # -> BooleanFilter | CharFilter | ChoiceFilter | ConcreteInFilter | ConcreteRangeFilter | DateFilter | DateTimeFilter | DurationFilter | ModelChoiceFilter | ModelMultipleChoiceFilter | NumberFilter | TimeFilter | UUIDFilter | dict[str, Any | bool | str | dict[str, str] | None] | dict[str, Any] | None:
        ...
    @classmethod
    def filter_for_lookup(
        cls, field, lookup_type
    ):  # -> tuple[None, dict[Any, Any]] | tuple[type[ChoiceFilter], dict[str, Any]] | tuple[type[NumberFilter] | type[CharFilter] | type[BooleanFilter] | type[DateFilter] | type[DateTimeFilter] | type[TimeFilter] | type[DurationFilter] | type[UUIDFilter] | type[ModelChoiceFilter] | Callable[..., dict[str, Any | bool | str | dict[str, str] | None]] | type[ModelMultipleChoiceFilter] | Callable[..., dict[str, Any]] | None, BooleanFilter | CharFilter | DateFilter | DateTimeFilter | DurationFilter | ModelChoiceFilter | ModelMultipleChoiceFilter | NumberFilter | TimeFilter | UUIDFilter | dict[str, Any | bool | str | dict[str, str] | None] | dict[str, Any]] | tuple[type[ConcreteInFilter], BooleanFilter | CharFilter | DateFilter | DateTimeFilter | DurationFilter | ModelChoiceFilter | ModelMultipleChoiceFilter | NumberFilter | TimeFilter | UUIDFilter | dict[str, Any | bool | str | dict[str, str] | None] | dict[str, Any]] | tuple[type[ConcreteRangeFilter], BooleanFilter | CharFilter | DateFilter | DateTimeFilter | DurationFilter | ModelChoiceFilter | ModelMultipleChoiceFilter | NumberFilter | TimeFilter | UUIDFilter | dict[str, Any | bool | str | dict[str, str] | None] | dict[str, Any]] | tuple[type[NumberFilter] | type[ModelChoiceFilter] | Callable[..., dict[str, Any | bool | str | dict[str, str] | None]] | type[CharFilter] | type[BooleanFilter] | type[DateFilter] | type[DateTimeFilter] | type[TimeFilter] | type[DurationFilter] | type[UUIDFilter] | type[ModelMultipleChoiceFilter] | Callable[..., dict[str, Any]], BooleanFilter | CharFilter | DateFilter | DateTimeFilter | DurationFilter | ModelChoiceFilter | ModelMultipleChoiceFilter | NumberFilter | TimeFilter | UUIDFilter | dict[str, Any | bool | str | dict[str, str] | None] | dict[str, Any]]:
        ...

class FilterSet(BaseFilterSet, metaclass=FilterSetMetaclass): ...

def filterset_factory(model, filterset=..., fields=...):  # -> type[FilterSet]:
    ...
