def deprecate(msg, level_modifier=...):  # -> None:
    ...

class MigrationNotice(DeprecationWarning):
    url = ...
    def __init__(self, message) -> None: ...

class RenameAttributesBase(type):
    renamed_attributes = ...
    def __new__(metacls, name, bases, attrs):  # -> Self:
        ...
    def get_name(cls, name): ...
    def __getattr__(cls, name):  # -> Any:
        ...
    def __setattr__(cls, name, value):  # -> None:
        ...

def try_dbfield(fn, field_class):  # -> None:
    ...
def get_all_model_fields(model):  # -> list[Any]:
    ...
def get_model_field(model, field_name):  # -> None:
    ...
def get_field_parts(model, field_name):  # -> list[Any] | None:
    ...
def resolve_field(
    model_field, lookup_expr
):  # -> tuple[Any | Field[Any, Any], Any | str] | None:
    ...
def handle_timezone(value, is_dst=...):  # -> datetime:
    ...
def verbose_field_name(
    model, field_name
):  # -> LiteralString | Literal['[invalid name]']:
    ...
def verbose_lookup_expr(lookup_expr):  # -> str:
    ...
def label_for_filter(model, field_name, lookup_expr, exclude=...):  # -> str | None:
    ...
def translate_validation(error_dict):  # -> ValidationError:
    ...
