from django import forms

class LinkWidget(forms.Widget):
    def __init__(self, attrs=..., choices=...) -> None: ...
    def value_from_datadict(self, data, files, name):  # -> Any:
        ...
    def render(self, name, value, attrs=..., choices=..., renderer=...):  # -> SafeText:
        ...
    def render_options(self, choices, selected_choices, name):  # -> LiteralString:
        ...
    def render_option(
        self, name, selected_choices, option_value, option_label
    ):  # -> str:
        ...
    def option_string(self):  # -> LiteralString:
        ...

class SuffixedMultiWidget(forms.MultiWidget):
    suffixes = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def suffixed(self, name, suffix):  # -> LiteralString:
        ...
    def get_context(self, name, value, attrs):  # -> dict[str, Any]:
        ...
    def value_from_datadict(self, data, files, name):  # -> list[Any]:
        ...
    def value_omitted_from_data(self, data, files, name):  # -> bool:
        ...
    def replace_name(self, output, index):  # -> str:
        ...
    def decompress(self, value):  # -> list[None] | Any:
        ...

class RangeWidget(SuffixedMultiWidget):
    template_name = ...
    suffixes = ...
    def __init__(self, attrs=...) -> None: ...
    def decompress(self, value):  # -> list[Any] | list[None]:
        ...

class DateRangeWidget(RangeWidget):
    suffixes = ...

class LookupChoiceWidget(SuffixedMultiWidget):
    suffixes = ...
    def decompress(self, value):  # -> list[None]:
        ...

class BooleanWidget(forms.Select):
    def __init__(self, attrs=...) -> None: ...
    def render(self, name, value, attrs=..., renderer=...):  # -> SafeText:
        ...
    def value_from_datadict(self, data, files, name): ...

class BaseCSVWidget(forms.Widget):
    surrogate = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def value_from_datadict(self, data, files, name):  # -> list[Any] | Any | None:
        ...
    def render(self, name, value, attrs=..., renderer=...):  # -> SafeText:
        ...

class CSVWidget(BaseCSVWidget, forms.TextInput):
    def __init__(self, *args, attrs=..., **kwargs) -> None: ...

class QueryArrayWidget(BaseCSVWidget, forms.TextInput):
    def value_from_datadict(self, data, files, name):  # -> list[Any]:
        ...
