class KeepContext:
    def __init__(self, context, keys) -> None: ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, type, value, traceback):  # -> None:  # noqa: A002
        ...
