"""
This type stub file was generated by pyright.
"""

from .layout import Div, Field, LayoutObject, TemplateNameMixin

class PrependedAppendedText(Field):
    """
    Layout object for rendering a field with prepended and appended text.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    field : str
        The name of the field to be rendered.
    prepended_text : str, optional
        The prepended text, can be HTML like, by default None
    appended_text : str, optional
        The appended text, can be HTML like, by default None
    input_size : str, optional
        For Bootstrap4+ additional classes to customise the input-group size
        e.g. ``input-group-sm``. By default None
    active : bool
        For Bootstrap3, a boolean to render the text active. By default
        ``False``.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

         PrependedAppendedText('amount', '$', '.00')
    """

    template = ...
    def __init__(
        self,
        field,
        prepended_text=...,
        appended_text=...,
        input_size=...,
        *,
        active=...,
        css_class=...,
        wrapper_class=...,
        template=...,
        **kwargs,
    ) -> None: ...
    def render(self, form, context, template_pack=..., extra_context=..., **kwargs): ...

class AppendedText(PrependedAppendedText):
    """
    Layout object for rendering a field with appended text.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    field : str
        The name of the field to be rendered.
    text : str
        The appended text, can be HTML like.
    input_size : str, optional
        For Bootstrap4+ additional classes to customise the input-group size
        e.g. ``input-group-sm``. By default None
    active : bool
        For Bootstrap3, a boolean to render the text active. By default
        ``False``.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

         AppendedText('amount', '.00')
    """
    def __init__(
        self,
        field,
        text,
        *,
        input_size=...,
        active=...,
        css_class=...,
        wrapper_class=...,
        template=...,
        **kwargs,
    ) -> None: ...

class PrependedText(PrependedAppendedText):
    """
    Layout object for rendering a field with prepended text.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    field : str
        The name of the field to be rendered.
    text : str
        The prepended text, can be HTML like.
    input_size : str, optional
        For Bootstrap4+ additional classes to customise the input-group size
        e.g. ``input-group-sm``. By default None
    active : bool
        For Bootstrap3, a boolean to render the text active. By default
        ``False``.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

         PrependedText('amount', '$')
    """
    def __init__(
        self,
        field,
        text,
        *,
        input_size=...,
        active=...,
        css_class=...,
        wrapper_class=...,
        template=...,
        **kwargs,
    ) -> None: ...

class FormActions(LayoutObject):
    """
    Bootstrap layout object. It wraps fields in a <div class="form-actions">

    Attributes
    ----------
    template: str
        The default template which this Layout Object will be rendered with.

    Parameters
    ----------

    *fields : HTML or BaseInput
        The layout objects to render within the ``ButtonHolder``. It should
        only hold `HTML` and `BaseInput` inherited objects.
    css_id : str, optional
        A custom DOM id for the layout object which will be added to the
        ``<div>`` if provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied to the ``<div>``. By default
        None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.

    Examples
    --------

    An example using ``FormActions`` in your layout::

        FormActions(
            HTML(<span style="display: hidden;">Information Saved</span>),
            Submit('Save', 'Save', css_class='btn-primary')
        )
    """

    template = ...
    def __init__(
        self, *fields, css_id=..., css_class=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class InlineCheckboxes(Field):
    """
    Layout object for rendering checkboxes inline.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    *fields : str
        Usually a single field, but can be any number of fields, to be rendered
        with the same attributes applied.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        InlineCheckboxes('field_name')
    """

    template = ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class InlineRadios(Field):
    """
    Layout object for rendering radiobuttons inline.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    *fields : str
        Usually a single field, but can be any number of fields, to be rendered
        with the same attributes applied.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        InlineRadios('field_name')
    """

    template = ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class FieldWithButtons(Div):
    """
    A layout object for rendering a single field with any number of buttons.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the wrapping ``<div>``. By default None.

    Parameters
    ----------

    *fields : str or LayoutObject
        The first positional argument is the field. This can be either the
        name of the field as a string or an instance of `Field`. Following
        arguments will be rendered as buttons.
    input_size : str
        Additional CSS class to change the size of the input. e.g.
        "input-group-sm".
    css_id : str, optional
        A DOM id for the layout object which will be added to the wrapping
        ``<div>`` if provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the wrapping
        ``<div>``.

    Examples
    --------

    Example::

        FieldWithButtons(
            Field("password1", css_class="span4"),
            StrictButton("Go!", css_id="go-button"),
            input_size="input-group-sm",
        )
    """

    template = ...
    field_template = ...
    def __init__(
        self, *fields, input_size=..., css_id=..., css_class=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., extra_context=..., **kwargs): ...

class StrictButton(TemplateNameMixin):
    """
    Layout object for rendering an HTML button in a ``<button>`` tag.

    Attributes
    ----------
    template: str
        The default template which this Layout Object will be rendered
        with.
    field_classes : str
        The CSS classes to be applied to the button. By defult "btn".

    Parameters
    ----------
    content : str
        The content of the button. This content is context aware, to bring
        this to life see the examples section.
    css_id : str, optional
        A custom DOM id for the layout object which will be added to the
        ``<button>`` if provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied to the ``<button>``. By default
        None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to `flatatt` and converted into
        key="value", pairs. These attributes are added to the ``<button>``.

    Examples
    --------

    In your ``Layout``::

        StrictButton("button content", css_class="extra")

    The content of the button is context aware, so you can do things like::

        StrictButton("Button for {{ user.username }}")
    """

    template = ...
    field_classes = ...
    def __init__(
        self, content, css_id=..., css_class=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class Container(Div):
    """
    Base class used for `Tab` and `AccordionGroup`, represents a basic
    container concept.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default "".

    Parameters
    ----------
    name : str
        The name of the container.
    *fields : str, LayoutObject
        Any number of fields as positional arguments to be rendered within
        the container.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.
    """

    css_class = ...
    def __init__(
        self,
        name,
        *fields,
        css_id=...,
        css_class=...,
        template=...,
        active=...,
        **kwargs,
    ) -> None: ...
    def __contains__(self, field_name):  # -> bool:
        """
        check if field_name is contained within tab.
        """

class ContainerHolder(Div):
    """
    Base class used for `TabHolder` and `Accordion`, groups containers.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default None.

    Parameters
    ----------
    *fields : str, LayoutObject
        Any number of fields or layout objects as positional arguments to be
        rendered within the ``<div>``.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.
    """
    def first_container_with_errors(self, errors):  # -> None:
        """
        Returns the first container with errors, otherwise returns None.
        """

    def open_target_group_for_form(self, form):
        """
        Makes sure that the first group that should be open is open.
        This is either the first group with errors or the first group
        in the container, unless that first group was originally set to
        active=False.
        """

class Tab(Container):
    """
    Tab object. It wraps fields in a div whose default class is "tab-pane" and
    takes a name as first argument.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default "".

    Parameters
    ----------
    name : str
        The name of the container.
    *fields : str, LayoutObject
        Any number of fields as positional arguments to be rendered within
        the container.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        Tab('tab_name', 'form_field_1', 'form_field_2', 'form_field_3')
    """

    css_class = ...
    link_template = ...
    def render_link(self, template_pack=..., **kwargs):  # -> SafeString:
        """
        Render the link for the tab-pane. It must be called after render so css_class is updated
        with active if needed.
        """

    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class TabHolder(ContainerHolder):
    """
    TabHolder object. It wraps Tab objects in a container.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default None.

    Parameters
    ----------
    *fields : str, LayoutObject
        Any number of fields or layout objects as positional arguments to be
        rendered within the ``<div>``.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.

    Examples
    --------
    Example::

        TabHolder(
            Tab('form_field_1', 'form_field_2'),
            Tab('form_field_3')
        )
    """

    template = ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class AccordionGroup(Container):
    """
    Accordion Group (pane) object. It wraps given fields inside an accordion
    tab. It takes accordion tab name as first argument.

    Tab object. It wraps fields in a div whose default class is "tab-pane" and
    takes a name as first argument.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default "".

    Parameters
    ----------
    name : str
        The name of the container.
    *fields : str, LayoutObject
        Any number of fields as positional arguments to be rendered within
        the container.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.

    Examples
    --------
    Example::

        AccordionGroup("group name", "form_field_1", "form_field_2")
    """

    template = ...
    data_parent = ...

class Accordion(ContainerHolder):
    """
    Accordion menu object. It wraps `AccordionGroup` objects in a container

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    css_class : str, optional
        CSS classes to be applied to the ``<div>``. By default None.

    Parameters
    ----------
    *accordion_groups : str, LayoutObject
        Any number of layout objects as positional arguments to be rendered
        within the ``<div>``.
    css_id : str, optional
        A DOM id for the layout object which will be added to the ``<div>`` if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        Accordion(
            AccordionGroup("group name", "form_field_1", "form_field_2"),
            AccordionGroup("another group name", "form_field")
        )
    """

    template = ...
    def __init__(
        self, *accordion_groups, css_id=..., css_class=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class Alert(Div):
    """
    Generates markup in the form of an alert dialog.

    Attributes
    ----------
    template: str
        The default template which this Layout Object will be rendered
        with.
    css_class : str
        The CSS classes to be applied to the alert. By defult "alert".

    Parameters
    ----------
    content : str
        The content of the alert.
    dismiss : bool
        If true the alert contains a button to dismiss the alert. By default
        True.
    block : str, optional
        Additional CSS classes to be applied to the ``<button>``. By default
        None.
    css_id : str, optional
        A DOM id for the layout object which will be added to the alert if
        provided. By default None.
    css_class : str, optional
        Additional CSS classes to be applied in addition to those declared by
        the class itself. By default None.
    template : str, optional
        Overrides the default template, if provided. By default None.
    **kwargs : dict, optional
        Additional attributes are passed to ``flatatt`` and converted into
        key="value", pairs. These attributes are then available in the template
        context.

    Examples
    --------

    Example::

        Alert(content='<strong>Warning!</strong> Best check yo self, you're not looking too good.')

    """

    template = ...
    css_class = ...
    def __init__(
        self,
        content,
        dismiss=...,
        block=...,
        css_id=...,
        css_class=...,
        template=...,
        **kwargs,
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class UneditableField(Field):
    """
    Layout object for rendering fields as uneditable in bootstrap.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    fields : str
        The name of the field.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        UneditableField('field_name', css_class="input-xlarge")
    """

    template = ...
    def __init__(
        self, field, css_class=..., wrapper_class=..., template=..., **kwargs
    ) -> None: ...

class InlineField(Field):
    """
    Layout object for rendering fields as Inline in bootstrap.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.
    attrs : dict
        Attributes to be applied to the field. These are converted into html
        attributes. e.g. ``data_id: 'test'`` in the attrs dict will become
        ``data-id='test'`` on the field's ``<input>``.

    Parameters
    ----------
    *fields : str
        Usually a single field, but can be any number of fields, to be rendered
        with the same attributes applied.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default ``None``.
    wrapper_class: str, optional
        CSS classes to be used when rendering the Field. This class is usually
        applied to the ``<div>`` which wraps the Field's ``<label>`` and
        ``<input>`` tags. By default ``None``.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        InlineField('field_name')
    """

    template = ...

class Modal(LayoutObject):
    """
    Boostrap layout object for rendering crispy forms objects inside a
    bootstrap modal.

    Attributes
    ----------
    template : str
        The default template which this Layout Object will be rendered
        with.

    Parameters
    ----------
    *fields : str
        The fields to be rendered within the modal.
    template : str, optional
        Overrides the default template, if provided. By default ``None``.
    css_id: str, optional
        The modal's DOM id. By default ``modal_id``.
    title: str, optional
        Text to display in the modal's header which will be wrapped in an
        ``<H5>`` tag. By default ``Modal Title``.
    title_id: str, optional
        The title's DOM id. By default ``modal_title_id``.
    css_class : str, optional
        CSS classes to be applied to the field. These are added to any classes
        included in the ``attrs`` dict. By default None.
    title_class: str, optional
        Additional CSS classes to be applied to the title. By default None.
    **kwargs : dict, optional
        Additional attributes are converted into key="value", pairs. These
        attributes are added to the ``<div>``.

    Examples
    --------

    Example::

        Modal(
            'field1',
            Div('field2'),
            css_id="modal-id-ex",
            css_class="modal-class-ex,
            title="This is my modal",
        )
    """

    template = ...
    def __init__(
        self,
        *fields,
        template=...,
        css_id=...,
        title=...,
        title_id=...,
        css_class=...,
        title_class=...,
        **kwargs,
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...
