"""This type stub file was generated by pyright."""  # noqa: PYI021

from dataclasses import dataclass
from typing import Any

from django import forms
from django.utils.functional import _StrOrPromise  # pyright: ignore[reportPrivateUsage]
from django.utils.safestring import SafeString

@dataclass
class Pointer:
    positions: list[int]
    name: str

class TemplateNameMixin:
    template: str

    def get_template_name(self, template_pack: str) -> str: ...

class LayoutObject(TemplateNameMixin):
    def __getitem__(self, slice):  # -> Any:  # noqa: A002
        ...
    def __setitem__(self, slice, value):  # -> None:  # noqa: A002
        ...
    def __delitem__(self, slice):  # -> None:  # noqa: A002
        ...
    def __len__(self):  # -> int:
        ...
    def __getattr__(self, name):  # -> Any:
        ...
    def get_field_names(self, index=...):  # -> Any | list[Any]:
        ...
    def get_layout_objects(
        self,
        *LayoutClasses,  # noqa: N803
        index=...,
        max_level=...,
        greedy=...,
    ):  # -> Any | list[Any]:
        ...
    def get_rendered_fields(
        self, form, context, template_pack=..., **kwargs
    ):  # -> SafeString:
        ...

class Layout(LayoutObject):
    def __init__(self, *fields) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class ButtonHolder(LayoutObject):
    template = ...
    def __init__(self, *fields, css_id=..., css_class=..., template=...) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class BaseInput(TemplateNameMixin):
    template: str = "%s/layout/baseinput.html"
    field_classes: str = ""

    name: str
    value: _StrOrPromise
    id: str
    attrs: dict[str, str]
    flat_attrs: str

    def __init__(
        self,
        name: str,
        value: _StrOrPromise,
        *,
        css_id: str | None = None,
        css_class: str | None = None,
        template: str | None = None,
        **kwargs: Any,  # pyright: ignore[reportAny, reportExplicitAny]
    ) -> None: ...
    def render(
        self,
        form: type[forms.Form],
        context: dict[str, Any],  # pyright: ignore[reportExplicitAny]
        template_pack: str = ...,
        **kwargs: Any,  # pyright: ignore[reportAny, reportExplicitAny]
    ) -> SafeString: ...

class Submit(BaseInput):
    input_type: str = "submit"
    field_classes: str = "btn btn-primary"

class Button(BaseInput):
    input_type = ...
    field_classes = ...

class Hidden(BaseInput):
    input_type = ...
    field_classes = ...

class Reset(BaseInput):
    input_type = ...
    field_classes = ...

class Fieldset(LayoutObject):
    template = ...
    def __init__(
        self, legend, *fields, css_class=..., css_id=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class MultiField(LayoutObject):
    template = ...
    field_template = ...
    def __init__(
        self,
        label,
        *fields,
        label_class=...,
        help_text=...,
        css_class=...,
        css_id=...,
        template=...,
        field_template=...,
        **kwargs,
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class Div(LayoutObject):
    template = ...
    css_class = ...
    def __init__(
        self, *fields, css_id=..., css_class=..., template=..., **kwargs
    ) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class Row(Div):
    template = ...

class Column(Div):
    template = ...

class HTML:
    def __init__(self, html) -> None: ...
    def render(self, form, context, template_pack=..., **kwargs):  # -> SafeString:
        ...

class Field(LayoutObject):
    template = ...
    attrs = ...
    def __init__(
        self, *fields, css_class=..., wrapper_class=..., template=..., **kwargs
    ) -> None: ...
    def render(
        self, form, context, template_pack=..., extra_context=..., **kwargs
    ):  # -> SafeString:
        ...

class MultiWidgetField(Field):
    def __init__(self, *fields, attrs=..., template=..., wrapper_class=...) -> None: ...
