# pyright: reportUnknownParameterType=false, reportMissingParameterType=false
class LayoutSlice:
    args_first = ...  # pyright: ignore[reportUnannotatedClassAttribute, reportAny]
    def __init__(self, layout, key) -> None: ...
    def wrapped_object(
        self,
        LayoutClass,  # noqa: N803
        fields,
        *args,
        **kwargs,
    ):  # -> Container | Fieldset | MultiField:
        ...
    def pre_map(self, function):  # -> None:
        ...
    def wrap(self, LayoutClass, *args, **kwargs):  # -> None:  # noqa: N803
        ...
    def wrap_once(self, LayoutClass, *args, **kwargs):  # -> None:  # noqa: N803
        ...
    def wrap_together(self, LayoutClass, *args, **kwargs):  # -> None:  # noqa: N803
        ...
    def map(self, function):  # -> None:
        ...
    def update_attributes(self, **original_kwargs):  # -> None:
        ...
