# Generated by Django 5.0.3 on 2024-03-24 18:23

import incredible_data.bins.models.bins_container_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.CharField(default=incredible_data.bins.models.bins_container_models.short_uuid, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
