# Generated by Django 5.0.3 on 2024-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_alter_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/', verbose_name='contents image'),
        ),
    ]
