# Generated by Django 5.0.4 on 2024-05-21 19:23

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_container_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=5, max_length=5, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
