# Generated by Django 5.0.6 on 2024-05-22 17:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_alter_container_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='image',
        ),
        migrations.CreateModel(
            name='ContainerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attachment', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='attachment')),
                ('attachment_type', models.CharField(choices=[('image', 'image'), ('document', 'document'), ('manual', 'manual'), ('other', 'other')], max_length=20, verbose_name='attachment type')),
                ('primary', models.BooleanField(default=False, verbose_name='primary attachment')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bins.container', verbose_name='container')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.AddConstraint(
            model_name='containerattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('container',), name='unique_primary_attachment'),
        ),
    ]
