# Generated by Django 5.0.6 on 2024-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0007_remove_container_image_containerattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerattachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
