# Generated by Django 5.0.6 on 2024-05-22 19:22

from django.db import migrations

from incredible_data.helpers.functions import create_media_name

def fix_attachment_names(apps, schema_editor):
    ContainerAttachment = apps.get_model("bins", "ContainerAttachment")
    for attachment in ContainerAttachment.objects.filter(name=""):
        attachment.name = create_media_name(attachment.attachment)
        attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0008_containerattachment_name'),
    ]

    operations = [
        migrations.RunPython(fix_attachment_names),
    ]
