[phase.setup]
nixPkgs = ["...", "poetry"]

[phase.install]
cmds = ["poetry install --with production --no-interactive --no-ansi"]

[start]
cmd = "python manage.py migrate && ./compose/production/django/start"
