[variables]
NIXPACKS_POETRY_VERSION = "1.8.3"

[phases.setup]
nixPkgs = ["...", "poetry"]

[phases.install]
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && poetry install --with production --no-interaction --no-ansi']

[phases.release]
cmds = ["python manage.py migrate && python manage.py collectstatic --no-input && python manage.py compress"]

[phases.deploy]
cmds = ["python manage.py createsuperuser --noinput"]

[start]
cmd = "gunicorn config.wsgi --bind 0.0.0.0:8000"
