databases:
  - name: incredible-data-db
    plan: free
    databaseName: incredible_data
    user: incredible_data_user

services:
  - type: worker
    name: celery-worker
    region: oregon
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app config.celery_app worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incredible-data-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
  - type: web
    plan: free
    name: incredible-data-web
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incredible-data-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: cache-redis
          type: redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []
  - type: redis
    name: cache-redis
    region: oregon
    plan: starter
    ipAllowList: []
