"""This type stub file was generated by pyright."""  # noqa: PYI021
# pyright: reportMissingParameterType=false, reportUnknownParameterType=false

import enum
from collections.abc import Callable, Iterable, Mapping, Sized
from typing import Any, Generic, Literal, Protocol, TypeVar, overload, override

from django.core.files.uploadedfile import UploadedFile
from django.core.paginator import Page, Paginator
from django.db import models
from django.forms import ModelForm
from django.http import HttpRequest, HttpResponseBase, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import URLPattern, URLResolver
from django.utils.datastructures import MultiValueDict
from django.utils.decorators import classonlymethod
from django.utils.functional import classproperty
from django.views.generic import View
from django_filters.filterset import FilterSet

class ViewProtocol(Protocol):
    url_base: str
    lookup_url_kwarg: str | None
    lookup_field: str
    path_converter: str

class Role(enum.Enum):
    LIST = "list"
    CREATE = "create"
    DETAIL = "detail"
    UPDATE = "update"
    DELETE = "delete"
    def handlers(self) -> dict[str, str]: ...
    def extra_initkwargs(self) -> dict[str, str]: ...
    @property
    def url_name_component(
        self,
    ) -> Literal["list", "create", "detail", "update", "delete"]: ...
    def url_pattern(
        self, view_cls: type[ViewProtocol | CRUDView[_ModelT_co]]
    ) -> str: ...
    def get_url(
        self, view_cls: type[ViewProtocol | CRUDView[_ModelT_co]]
    ) -> URLPattern: ...
    def reverse(
        self,
        view: ViewProtocol | CRUDView[_ModelT_co],
        object: _ModelT_co = ...,  # noqa: A002
    ) -> str: ...
    def maybe_reverse(
        self,
        view: ViewProtocol | CRUDView[_ModelT_co],
        object: _ModelT_co = ...,  # noqa: A002
    ) -> str | None: ...

_ModelT_co = TypeVar("_ModelT_co", bound=models.Model, covariant=True)
_KWargsT = TypeVar("_KWargsT")

class _SupportsPagination(Protocol[_ModelT_co], Sized, Iterable):  # pyright: ignore[reportMissingTypeArgument, reportGeneralTypeIssues]
    @overload
    def __getitem__(self, index: int, /) -> _ModelT_co: ...
    @overload
    def __getitem__(self, index: slice, /) -> _SupportsPagination[_ModelT_co]: ...

class CRUDView(View, Generic[_ModelT_co]):
    role: Role
    model: type[_ModelT_co] | None = None
    fields: Iterable[str] | None = None
    lookup_field: str = "pk"
    lookup_url_kwarg: str | None = None
    path_converter: str = "int"
    object: _ModelT_co | None = None
    queryset: models.QuerySet[_ModelT_co] | None = None
    form_class: type[ModelForm[_ModelT_co]] | None = None
    template_name: str | None = None
    context_object_name: str | None = None
    paginate_by: int | None = None
    page_kwarg: str = "page"
    allow_empty: bool = True
    template_name_suffix: str | None = None

    def __init__(
        self,
        model: _ModelT_co | None,
        queryset: models.QuerySet[_ModelT_co] | None,
        filterset_class: type[FilterSet[_ModelT_co]] | None = None,
        filterset_fields: None = None,
        **kwargs,
    ) -> None: ...
    def list(self, request: HttpRequest, *args, **kwargs) -> TemplateResponse: ...
    def detail(self, request: HttpRequest, *args, **kwargs) -> TemplateResponse: ...
    def show_form(self, request: HttpRequest, *args, **kwargs) -> TemplateResponse: ...
    def process_form(
        self, request: HttpRequest, *args, **kwargs
    ) -> HttpResponseRedirect | TemplateResponse: ...
    def confirm_delete(
        self, request: HttpRequest, *args, **kwargs
    ) -> TemplateResponse: ...
    def process_deletion(
        self, request: HttpRequest, *args, **kwargs
    ) -> HttpResponseRedirect: ...
    def get_queryset(self) -> models.QuerySet[_ModelT_co]: ...
    def get_object(self) -> _ModelT_co: ...
    def get_form_class(self) -> type[ModelForm[_ModelT_co]]: ...
    def get_form(
        self,
        data: Mapping[str, Any] = ...,  # pyright: ignore[reportExplicitAny]
        files: MultiValueDict[str, UploadedFile] = ...,
        **kwargs,
    ) -> ModelForm[_ModelT_co]: ...
    def form_valid(self, form: ModelForm[_ModelT_co]) -> HttpResponseRedirect: ...
    def form_invalid(self, form: ModelForm[_ModelT_co]) -> TemplateResponse: ...
    def get_success_url(self) -> str: ...
    def get_paginate_by(self) -> int | None: ...
    def get_paginator(
        self, queryset: _SupportsPagination[_ModelT_co], page_size: int | str
    ) -> Paginator[_ModelT_co]: ...
    def paginate_queryset(
        self, queryset: _SupportsPagination[_ModelT_co], page_size: int | str
    ) -> Page[_ModelT_co]: ...
    def get_filterset(
        self, queryset: models.QuerySet[_ModelT_co] | None = None
    ) -> FilterSet[_ModelT_co] | None: ...
    def get_context_object_name(self, is_list: bool = False) -> str | None: ...
    def get_context_data(
        self, **kwargs: _KWargsT
    ) -> dict[
        str,
        _KWargsT
        | CRUDView[_ModelT_co]
        | str
        | _ModelT_co
        | _SupportsPagination[_ModelT_co],
    ]: ...
    def get_template_names(self) -> list[str]: ...
    def render_to_response(self, context: dict[str, Any]) -> TemplateResponse: ...  # pyright: ignore[reportExplicitAny]
    @classonlymethod
    @override
    def as_view(cls, role: Role, **initkwargs) -> Callable[..., HttpResponseBase]: ...  # noqa: N805  # pyright: ignore[reportIncompatibleMethodOverride]
    @classproperty
    def url_base(cls) -> str: ...  # noqa: N805
    @classonlymethod
    def get_urls(
        cls,  # noqa: N805
        roles: Iterable[Role] | None = None,
    ) -> list[URLPattern | URLResolver]: ...
