"""
This type stub file was generated by pyright.
"""

import enum
from typing import Iterable, Protocol

from django.db import models
from django.urls import URLPattern, URLResolver
from django.utils.decorators import classonlymethod
from django.utils.functional import classproperty
from django.views.generic import View

class ViewProtocol(Protocol):
    url_base: str
    lookup_url_kwarg: str | None
    lookup_field: str
    path_converter: str

class Role(enum.Enum):
    LIST = ...
    CREATE = ...
    DETAIL = ...
    UPDATE = ...
    DELETE = ...
    def handlers(self):  # -> dict[str, str]:
        ...
    def extra_initkwargs(self):  # -> dict[str, str]:
        ...
    @property
    def url_name_component(
        self,
    ):  # -> Literal['list', 'create', 'detail', 'update', 'delete']:
        ...
    def url_pattern(self, view_cls: type[ViewProtocol | CRUDView]) -> str: ...
    def get_url(self, view_cls: type[ViewProtocol | CRUDView]) -> URLPattern: ...
    def reverse(self, view, object=...):  # -> str:
        ...
    def maybe_reverse(self, view, object=...):  # -> str | None:
        ...

class CRUDView(View):
    role: Role
    model: type[models.Model] | None = None
    fields: Iterable[str] | None = None
    lookup_field: str = "pk"
    lookup_url_kwarg: str | None = None
    path_converter: str = "int"
    object = ...
    queryset = ...
    form_class = ...
    template_name = ...
    context_object_name = ...
    paginate_by = ...
    page_kwarg = ...
    allow_empty = ...
    template_name_suffix = ...
    def list(self, request, *args, **kwargs):
        """GET handler for the list view."""
        ...

    def detail(self, request, *args, **kwargs):
        """GET handler for the detail view."""
        ...

    def show_form(self, request, *args, **kwargs):  # -> TemplateResponse:
        """GET handler for the create and update form views."""
        ...

    def process_form(
        self, request, *args, **kwargs
    ):  # -> HttpResponseRedirect | TemplateResponse:
        """POST handler for the create and update form views."""
        ...

    def confirm_delete(self, request, *args, **kwargs):
        """GET handler for the delete confirmation view."""
        ...

    def process_deletion(self, request, *args, **kwargs):
        """POST handler for the delete confirmation view."""
        ...

    def get_queryset(self):
        """
        Returns the base queryset for the view.

        Either used as a list of objects to display, or as the queryset
        from which to perform the individual object lookup.
        """
        ...

    def get_object(self):
        """
        Returns the object the view is displaying.
        """
        ...

    def get_form_class(self):  # -> type[ModelForm[Never]]:
        """
        Returns the form class to use in this view.
        """
        ...

    def get_form(self, data=..., files=..., **kwargs):  # -> ModelForm[Never]:
        """
        Returns a form instance.
        """
        ...

    def form_valid(self, form):  # -> HttpResponseRedirect:
        ...
    def form_invalid(self, form):  # -> TemplateResponse:
        ...
    def get_success_url(self):  # -> str:
        ...
    def get_paginate_by(self):  # -> None:
        """
        Returns the size of pages to use with pagination.
        """
        ...

    def get_paginator(self, queryset, page_size):  # -> Paginator[Any]:
        """
        Returns a paginator instance.
        """
        ...

    def paginate_queryset(self, queryset, page_size):  # -> Page[Any]:
        """
        Paginates a queryset, and returns a page object.
        """
        ...

    def get_filterset(self, queryset=...):  # -> FilterSet | Any | None:
        ...
    def get_context_object_name(self, is_list=...):  # -> None:
        """
        Returns a descriptive name to use in the context in addition to the
        default 'object'/'object_list'.
        """
        ...

    def get_context_data(self, **kwargs):  # -> dict[str, Any]:
        ...
    def get_template_names(self):  # -> list[Never] | list[str]:
        """
        Returns a list of template names to use when rendering the response.

        If `.template_name` is not specified, uses the
        "{app_label}/{model_name}{template_name_suffix}.html" model template
        pattern, with the fallback to the
        "neapolitan/object{template_name_suffix}.html" default templates.
        """
        ...

    def render_to_response(self, context):  # -> TemplateResponse:
        """
        Given a context dictionary, returns an HTTP response.
        """
        ...

    @classonlymethod
    def as_view(cls, role: Role, **initkwargs):  # -> Callable[..., HttpResponseBase]:
        """Main entry point for a request-response process."""
        ...

    @classproperty
    def url_base(cls) -> str: ...  # noqa: N805
    @classonlymethod
    def get_urls(cls, roles=...):  # -> list[Any]:
        """Classmethod to generate URL patterns for the view."""
        ...
