from appconf import AppConf
from django.conf import settings

"""Settings for Django-Select2."""
__all__ = ("Select2Conf", "settings")

class Select2Conf(AppConf):
    CACHE_BACKEND = ...
    CACHE_PREFIX = ...
    JS = ...
    CSS = ...
    THEME = ...
    I18N_PATH = ...
    I18N_AVAILABLE_LANGUAGES = ...
    JSON_ENCODER = ...
    class Meta:
        prefix = ...
