from django import forms

"""
Django-Select2 Widgets.

These components are responsible for rendering
the necessary HTML data markups. Since this whole
package is to render choices using Select2 JavaScript
library, hence these components are meant to be used
with choice fields.

Widgets are generally of tree types:
Light, Heavy and Model.

Light
~~~~~

They are not meant to be used when there
are too many options, say, in thousands.
This is because all those options would
have to be pre-rendered onto the page
and JavaScript would be used to search
through them. Said that, they are also one
the easiest to use. They are a
drop-in-replacement for Django's default
select widgets.

Heavy
~~~~~

They are suited for scenarios when the number of options
are large and need complex queries (from maybe different
sources) to get the options.

This dynamic fetching of options undoubtedly requires
Ajax communication with the server. Django-Select2 includes
a helper JS file which is included automatically,
so you need not worry about writing any Ajax related JS code.
Although on the server side you do need to create a view
specifically to respond to the queries.

Model
~~~~~

Model-widgets are a further specialized versions of Heavies.
These do not require views to serve Ajax requests.
When they are instantiated, they register themselves
with one central view which handles Ajax requests for them.

Heavy and Model widgets have respectively the word 'Heavy' and 'Model' in
their name.  Light widgets are normally named, i.e. there is no 'Light' word
in their names.

.. inheritance-diagram:: django_select2.forms
    :parts: 1

"""

class Select2Mixin:
    css_class_name = ...
    theme = ...
    empty_label = ...
    @property
    def i18n_name(self): ...
    def build_attrs(self, base_attrs, extra_attrs=...): ...
    def optgroups(self, name, value, attrs=...): ...
    @property
    def media(self):  # -> Media:
        ...

class Select2AdminMixin:
    theme = ...
    @property
    def media(self):  # -> Media:
        ...

class Select2TagMixin:
    def build_attrs(self, base_attrs, extra_attrs=...): ...

class Select2Widget(Select2Mixin, forms.Select): ...
class Select2MultipleWidget(Select2Mixin, forms.SelectMultiple): ...
class Select2TagWidget(Select2TagMixin, Select2Mixin, forms.SelectMultiple): ...

class HeavySelect2Mixin:
    dependent_fields = ...
    data_view = ...
    data_url = ...
    def __init__(self, attrs=..., choices=..., **kwargs) -> None: ...
    def get_url(self):  # -> str:
        ...
    def build_attrs(self, base_attrs, extra_attrs=...): ...
    def render(self, *args, **kwargs): ...
    def set_to_cache(self):  # -> None:
        ...

class HeavySelect2Widget(HeavySelect2Mixin, Select2Widget): ...
class HeavySelect2MultipleWidget(HeavySelect2Mixin, Select2MultipleWidget): ...
class HeavySelect2TagWidget(HeavySelect2Mixin, Select2TagWidget): ...

class ModelSelect2Mixin:
    model = ...
    queryset = ...
    search_fields = ...
    max_results = ...
    @property
    def empty_label(self):  # -> str | None:
        ...
    def __init__(self, *args, **kwargs) -> None: ...
    def set_to_cache(self):  # -> None:
        ...
    def filter_queryset(self, request, term, queryset=..., **dependent_fields): ...
    def get_queryset(self): ...
    def get_search_fields(self):  # -> list[Any]:
        ...
    def optgroups(
        self, name, value, attrs=...
    ):  # -> list[tuple[None, list[Any], Literal[0]]]:
        ...
    def label_from_instance(self, obj):  # -> str:
        ...
    def result_from_instance(self, obj, request):  # -> dict[str, Any | str]:
        ...

class ModelSelect2Widget(ModelSelect2Mixin, HeavySelect2Widget): ...
class ModelSelect2MultipleWidget(ModelSelect2Mixin, HeavySelect2MultipleWidget): ...
class ModelSelect2TagWidget(ModelSelect2Mixin, HeavySelect2TagWidget): ...
