"""
This type stub file was generated by pyright.
"""

from django import forms

class ColorField(forms.CharField):
    default_validators = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


