"""
This type stub file was generated by pyright.
"""

from rest_framework.serializers import CharField

class ColorField(CharField):
    default_error_messages = ...
    def to_internal_value(self, data): # -> str:
        ...
    


