"""
This type stub file was generated by pyright.
"""

def get_image_background_color(img, img_format: str): # -> str:
    ...

def get_image_file_background_color(img_file, img_format: str): # -> str:
    ...

def get_random_string(): # -> str:
    ...

