"""
This type stub file was generated by pyright.
"""

from django.conf import settings
from django.forms import TextInput

class ColorWidget(TextInput):
    template_name = ...
    class Media:
        if settings.DEBUG:
            css = ...
            js = ...
        else:
            css = ...
            js = ...
    
    
    def get_context(self, name, value, attrs=...): # -> dict[Any, Any]:
        ...
    
    def render(self, name, value, attrs=..., renderer=...): # -> SafeText:
        ...
    


