from django.forms import TextInput

class ColorWidget(TextInput):
    template_name = ...
    class Media:
        css = ...
        js = ...

    def get_context(self, name, value, attrs=...):  # -> dict[Any, Any]:
        ...
    def render(self, name, value, attrs=..., renderer=...):  # -> SafeText:
        ...
