class TableExport:
    CSV = ...
    JSON = ...
    LATEX = ...
    ODS = ...
    TSV = ...
    XLS = ...
    XLSX = ...
    YAML = ...
    FORMATS = ...
    def __init__(
        self, export_format, table, exclude_columns=..., dataset_kwargs=...
    ) -> None: ...
    def table_to_dataset(
        self, table, exclude_columns, dataset_kwargs=...
    ):  # -> Dataset:
        ...
    @classmethod
    def is_valid_format(cls, export_format):  # -> bool:
        ...
    def content_type(self):  # -> str:
        ...
    def export(self): ...
    def response(self, filename=...):  # -> HttpResponse:
        ...
