"""
This type stub file was generated by pyright.
"""

class TableExport:
    """
    Export data from a table to the file type specified.

    Arguments:
        export_format (str): one of `csv, json, latex, ods, tsv, xls, xlsx, yaml`

        table (`~.Table`): instance of the table to export the data from

        exclude_columns (iterable): list of column names to exclude from the export

        dataset_kwargs (dictionary): passed as `**kwargs` to `tablib.Dataset` constructor

    """
    CSV = ...
    JSON = ...
    LATEX = ...
    ODS = ...
    TSV = ...
    XLS = ...
    XLSX = ...
    YAML = ...
    FORMATS = ...
    def __init__(self, export_format, table, exclude_columns=..., dataset_kwargs=...) -> None:
        ...
    
    def table_to_dataset(self, table, exclude_columns, dataset_kwargs=...): # -> Dataset:
        """Transform a table to a tablib dataset."""
        ...
    
    @classmethod
    def is_valid_format(self, export_format): # -> bool:
        """
        Returns true if `export_format` is one of the supported export formats
        """
        ...
    
    def content_type(self): # -> str:
        """
        Returns the content type for the current export format
        """
        ...
    
    def export(self):
        """
        Returns the string/bytes for the current export format
        """
        ...
    
    def response(self, filename=...): # -> HttpResponse:
        """
        Builds and returns a `HttpResponse` containing the exported data

        Arguments:
            filename (str): if not `None`, the filename is attached to the
                `Content-Disposition` header of the response.
        """
        ...
    


