from .export import TableExport

class ExportMixin:
    export_class = TableExport
    export_name = ...
    export_trigger_param = ...
    exclude_columns = ...
    dataset_kwargs = ...
    export_formats = ...
    def get_export_filename(self, export_format):  # -> str:
        ...
    def get_dataset_kwargs(self):  # -> None:
        ...
    def create_export(self, export_format):  # -> HttpResponse:
        ...
    def render_to_response(self, context, **kwargs):  # -> HttpResponse:
        ...
