from typing import Any, TypeVar

_ColumnT = TypeVar("_ColumnT", bound=Column)

class Library:
    columns: list[Column]
    def __init__(self) -> None: ...
    def register(self, column: type[_ColumnT]) -> type[_ColumnT]: ...
    def column_for_field(self, field: object, **kwargs: Any) -> Column: ...

library: Library = ...

class LinkTransform:
    viewname = ...
    accessor = ...
    attrs = ...
    def __init__(self, url=..., accessor=..., attrs=..., reverse_args=...) -> None: ...
    def compose_url(self, **kwargs):  # -> object | str | None:
        ...
    def call_reverse(self, record):  # -> str:
        ...
    def get_attrs(self, **kwargs):  # -> AttributeDict:
        ...
    def __call__(self, content, **kwargs):  # -> SafeString:
        ...

@library.register
class Column:
    creation_counter: int = 0
    empty_values: tuple[None | str, ...] = (None, "")
    link = ...
    _explicit: bool = False
    def __init__(
        self,
        verbose_name=...,
        accessor=...,
        default=...,
        visible=...,
        orderable=...,
        attrs=...,
        order_by=...,
        empty_values=...,
        localize=...,
        footer=...,
        exclude_from_export=...,
        linkify=...,
        initial_sort_descending=...,
    ) -> None: ...
    @property
    def default(self):  # -> object | None:
        ...
    @property
    def header(self):  # -> None:
        ...
    def footer(self, bound_column, table):  # -> object | Literal[''] | None:
        ...
    def render(self, value): ...
    def value(self, **kwargs):  # -> None:
        ...
    def order(self, queryset, is_descending):  # -> tuple[Any, Literal[False]]:
        ...
    @classmethod
    def from_field(cls, field, **kwargs):  # -> Column | None:
        ...

class BoundColumn:
    def __init__(self, table, column, name) -> None: ...
    @property
    def attrs(self):  # -> dict[Any, Any]:
        ...
    def get_td_class(self, td_attrs):  # -> LiteralString | None:
        ...
    def get_th_class(self, th_attrs):  # -> LiteralString | None:
        ...
    @property
    def default(self): ...
    @property
    def header(self):  # -> SafeData | Any:
        ...
    @property
    def footer(self):  # -> None:
        ...
    def has_footer(self):  # -> bool:
        ...
    @property
    def order_by(self):  # -> OrderByTuple:
        ...
    @property
    def order_by_alias(self):  # -> OrderBy:
        ...
    @property
    def is_ordered(self):  # -> bool:
        ...
    @property
    def orderable(self): ...
    @property
    def verbose_name(self):  # -> SafeData | Any:
        ...
    @property
    def visible(self): ...
    @property
    def localize(self): ...

class BoundColumns:
    def __init__(self, table, base_columns) -> None: ...
    def iternames(self):  # -> Generator[Any, None, None]:
        ...
    def names(self):  # -> list[Any]:
        ...
    def iterall(self):  # -> Generator[Any, None, None]:
        ...
    def all(self):  # -> list[Any]:
        ...
    def iteritems(self):  # -> Generator[tuple[Any, Any], Any, None]:
        ...
    def items(self):  # -> list[tuple[Any, Any]]:
        ...
    def iterorderable(self):  # -> Generator[Any, None, None]:
        ...
    def itervisible(self):  # -> Generator[Any, None, None]:
        ...
    def hide(self, name):  # -> None:
        ...
    def show(self, name):  # -> None:
        ...
    def __iter__(self):  # -> Generator[Any, None, None]:
        ...
    def __contains__(self, item):  # -> bool:
        ...
    def __len__(self):  # -> int:
        ...
    def __getitem__(self, index): ...
