"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TypeVar

_ColumnT = TypeVar("_ColumnT", bound=Column)

class Library:
    columns: list[Column]
    def __init__(self) -> None: ...
    def register(self, column: type[_ColumnT]) -> type[_ColumnT]: ...
    def column_for_field(self, field: object, **kwargs: Any) -> Column: ...

library: Library = ...

class LinkTransform:
    """Object used to generate attributes for the `<a>`-tag to wrap the cell content in."""

    viewname = ...
    accessor = ...
    attrs = ...
    def __init__(self, url=..., accessor=..., attrs=..., reverse_args=...) -> None:
        """
        arguments:
            url (callable): If supplied, the result of this callable will be used as ``href`` attribute.
            accessor (Accessor): if supplied, the accessor will be used to decide on which object
                ``get_absolute_url()`` is called.
            attrs (dict): Customize attributes for the ``<a>`` tag.
                Values of the dict can be either static text or a
                callable. The callable can optionally declare any subset
                of the following keyword arguments: value, record, column,
                bound_column, bound_row, table. These arguments will then
                be passed automatically.
            reverse_args (dict, tuple): Arguments to ``django.urls.reverse()``. If dict, the arguments
                are assumed to be keyword arguments to ``reverse()``, if tuple, a ``(viewname, args)``
                or ``(viewname, kwargs)``
        """
        ...

    def compose_url(self, **kwargs):  # -> object | str | None:
        ...
    def call_reverse(self, record):  # -> str:
        """
        Prepares the arguments to reverse() for this record and calls reverse()
        """
        ...

    def get_attrs(self, **kwargs):  # -> AttributeDict:
        ...
    def __call__(self, content, **kwargs):  # -> SafeString:
        ...

@library.register
class Column:
    creation_counter: int = 0
    empty_values: tuple[None | str, ...] = (None, "")
    link = ...
    _explicit: bool = False
    def __init__(
        self,
        verbose_name=...,
        accessor=...,
        default=...,
        visible=...,
        orderable=...,
        attrs=...,
        order_by=...,
        empty_values=...,
        localize=...,
        footer=...,
        exclude_from_export=...,
        linkify=...,
        initial_sort_descending=...,
    ) -> None: ...
    @property
    def default(self):  # -> object | None:
        ...
    @property
    def header(self):  # -> None:
        """
        The value used for the column heading (e.g. inside the ``<th>`` tag).

        By default this returns `~.Column.verbose_name`.

        :returns: `unicode` or `None`

        .. note::

            This property typically is not accessed directly when a table is
            rendered. Instead, `.BoundColumn.header` is accessed which in turn
            accesses this property. This allows the header to fallback to the
            column name (it is only available on a `.BoundColumn` object hence
            accessing that first) when this property doesn't return something
            useful.
        """
        ...

    def footer(self, bound_column, table):  # -> object | Literal[''] | None:
        """Return the content of the footer, if specified."""
        ...

    def render(self, value):
        """
        Return the content for a specific cell.

        This method can be overridden by :ref:`table.render_FOO` methods on the
        table or by subclassing `.Column`.

        If the value for this cell is in `.empty_values`, this method is
        skipped and an appropriate default value is rendered instead.
        Subclasses should set `.empty_values` to ``()`` if they want to handle
        all values in `.render`.
        """
        ...

    def value(self, **kwargs):  # -> None:
        """
        Return the content for a specific cell for exports.

        Similar to `.render` but without any html content.
        This can be used to get the data in the formatted as it is presented but in a
        form that could be added to a csv file.

        The default implementation just calls the `render` function but any
        subclasses where `render` returns html content should override this
        method.

        See `LinkColumn` for an example.
        """
        ...

    def order(self, queryset, is_descending):  # -> tuple[Any, Literal[False]]:
        """
        Order the QuerySet of the table.

        This method can be overridden by :ref:`table.order_FOO` methods on the
        table or by subclassing `.Column`; but only overrides if second element
        in return tuple is True.

        returns:
            Tuple (QuerySet, boolean)
        """
        ...

    @classmethod
    def from_field(cls, field, **kwargs):  # -> Column | None:
        """
        Return a specialized column for the model field or `None`.

        Arguments:
            field (Model Field instance): the field that needs a suitable column
        Returns:
            `.Column` object or `None`

        If the column is not specialized for the given model field, it should
        return `None`. This gives other columns the opportunity to do better.

        If the column is specialized, it should return an instance of itself
        that is configured appropriately for the field.
        """
        ...

class BoundColumn:
    """
    A run-time version of `.Column`.

    The difference between `.BoundColumn` and `.Column`,
    is that `.BoundColumn` objects include the relationship between a `.Column` and a `.Table`.
    In practice, this means that a `.BoundColumn` knows the *"variable name"* given to the `.Column`
    when it was declared on the `.Table`.

    arguments:
        table (`~.Table`): The table in which this column exists
        column (`~.Column`): The type of column
        name (str): The variable name of the column used when defining the
                    `.Table`. In this example the name is ``age``::

                          class SimpleTable(tables.Table):
                              age = tables.Column()

    """
    def __init__(self, table, column, name) -> None: ...
    def __str__(self) -> str: ...
    @property
    def attrs(self):  # -> dict[Any, Any]:
        """
        Proxy to `.Column.attrs` but injects some values of our own.

        A ``th``, ``td`` and ``tf`` are guaranteed to be defined (irrespective
        of what is actually defined in the column attrs. This makes writing
        templates easier. ``tf`` is not actually a HTML tag, but this key name
        will be used for attributes for column's footer, if the column has one.
        """
        ...

    def get_td_class(self, td_attrs):  # -> LiteralString | None:
        """
        Returns the HTML class attribute for a data cell in this column
        """
        ...

    def get_th_class(self, th_attrs):  # -> LiteralString | None:
        """
        Returns the HTML class attribute for a header cell in this column
        """
        ...

    @property
    def default(self):
        """Returns the default value for this column."""
        ...

    @property
    def header(self):  # -> SafeData | Any:
        """The contents of the header cell for this column."""
        ...

    @property
    def footer(self):  # -> None:
        """The contents of the footer cell for this column."""
        ...

    def has_footer(self):  # -> bool:
        ...
    @property
    def order_by(self):  # -> OrderByTuple:
        """
        Return an `.OrderByTuple` of appropriately prefixed data source keys used to sort this column.

        See `.order_by_alias` for details.
        """
        ...

    @property
    def order_by_alias(self):  # -> OrderBy:
        """
        Return an `OrderBy` describing the current state of ordering for this column.

        The following attempts to explain the difference between `order_by`
        and `.order_by_alias`.

        `.order_by_alias` returns and `.OrderBy` instance that's based on
        the *name* of the column, rather than the keys used to order the table
        data. Understanding the difference is essential.

        Having an alias *and* a keys version is necessary because an N-tuple
        (of data source keys) can be used by the column to order the data, and
        it is ambiguous when mapping from N-tuple to column (since multiple
        columns could use the same N-tuple).

        The solution is to use order by *aliases* (which are really just
        prefixed column names) that describe the ordering *state* of the
        column, rather than the specific keys in the data source should be
        ordered.

        e.g.::

            >>> class SimpleTable(tables.Table):
            ...     name = tables.Column(order_by=("firstname", "last_name"))
            ...
            >>> table = SimpleTable([], order_by=('-name', ))
            >>> table.columns["name"].order_by_alias
            "-name"
            >>> table.columns["name"].order_by
            ("-first_name", "-last_name")

        The `OrderBy` returned has been patched to include an extra attribute
        ``next``, which returns a version of the alias that would be
        transitioned to if the user toggles sorting on this column, for example::

            not sorted -> ascending
            ascending  -> descending
            descending -> ascending

        This is useful otherwise in templates you'd need something like::

            {% if column.is_ordered %}
                {% querystring table.prefixed_order_by_field=column.order_by_alias.opposite %}
            {% else %}
                {% querystring table.prefixed_order_by_field=column.order_by_alias %}
            {% endif %}

        """
        ...

    @property
    def is_ordered(self):  # -> bool:
        ...
    @property
    def orderable(self):
        """Return whether this column supports ordering."""
        ...

    @property
    def verbose_name(self):  # -> SafeData | Any:
        """
        Return the verbose name for this column.

        In order of preference, this will return:
          1) The column's explicitly defined `verbose_name`
          2) The model's `verbose_name` with the first letter capitalized (if applicable)
          3) Fall back to the column name, with first letter capitalized.

        Any `verbose_name` that was not passed explicitly in the column
        definition is returned with the first character capitalized in keeping
        with the Django convention of `verbose_name` being defined in lowercase and
        uppercased as needed by the application.

        If the table is using `QuerySet` data, then use the corresponding model
        field's `~.db.Field.verbose_name`. If it is traversing a relationship,
        then get the last field in the accessor (i.e. stop when the
        relationship turns from ORM relationships to object attributes [e.g.
        person.upper should stop at person]).
        """
        ...

    @property
    def visible(self):
        """Return whether this column is visible."""
        ...

    @property
    def localize(self):
        """Return `True`, `False` or `None` as described in ``Column.localize``"""
        ...

class BoundColumns:
    """
    Container for spawning `.BoundColumn` objects.

    This is bound to a table and provides its `.Table.columns` property.
    It provides access to those columns in different ways (iterator,
    item-based, filtered and unfiltered etc), stuff that would not be possible
    with a simple iterator in the table class.

    A `BoundColumns` object is a container for holding `BoundColumn` objects.
    It provides methods that make accessing columns easier than if they were
    stored in a `list` or `dict`. `Columns` has a similar API to a `dict` (it
    actually uses a `~collections.OrderedDict` internally).

    At the moment you'll only come across this class when you access a
    `.Table.columns` property.

    Arguments:
        table (`.Table`): the table containing the columns
    """
    def __init__(self, table, base_columns) -> None: ...
    def iternames(self):  # -> Generator[Any, None, None]:
        ...
    def names(self):  # -> list[Any]:
        ...
    def iterall(self):  # -> Generator[Any, None, None]:
        """
        Return an iterator that exposes all `.BoundColumn` objects,
        regardless of visibility or sortability.
        """
        ...

    def all(self):  # -> list[Any]:
        ...
    def iteritems(self):  # -> Generator[tuple[Any, Any], Any, None]:
        """
        Return an iterator of ``(name, column)`` pairs (where ``column`` is a `BoundColumn`).

        This method is the mechanism for retrieving columns that takes into
        consideration all of the ordering and filtering modifiers that a table
        supports (e.g. `~Table.Meta.exclude` and `~Table.Meta.sequence`).
        """
        ...

    def items(self):  # -> list[tuple[Any, Any]]:
        ...
    def iterorderable(self):  # -> Generator[Any, None, None]:
        """
        Same as `BoundColumns.all` but only returns orderable columns.

        This is useful in templates, where iterating over the full
        set and checking ``{% if column.ordarable %}`` can be problematic in
        conjunction with e.g. ``{{ forloop.last }}`` (the last column might not
        be the actual last that is rendered).
        """
        ...

    def itervisible(self):  # -> Generator[Any, None, None]:
        """
        Same as `.iterorderable` but only returns visible `.BoundColumn` objects.

        This is geared towards table rendering.
        """
        ...

    def hide(self, name):  # -> None:
        """
        Hide a column.

        Arguments:
            name(str): name of the column
        """
        ...

    def show(self, name):  # -> None:
        """
        Show a column otherwise hidden.

        Arguments:
            name(str): name of the column
        """
        ...

    def __iter__(self):  # -> Generator[Any, None, None]:
        """Convenience API, alias of `.itervisible`."""
        ...

    def __contains__(self, item):  # -> bool:
        """
        Check if a column is contained within a `BoundColumns` object.

        *item* can either be a `~.BoundColumn` object, or the name of a column.
        """
        ...

    def __len__(self):  # -> int:
        """Return how many `~.BoundColumn` objects are contained (and visible)."""
        ...

    def __getitem__(self, index):
        """
        Retrieve a specific `~.BoundColumn` object.

        *index* can either be 0-indexed or the name of a column

        .. code-block:: python

            columns['speed']  # returns a bound column with name 'speed'
            columns[0]        # returns the first column
        """
        ...
