from .base import Column, library

@library.register
class BooleanColumn(Column):
    def __init__(self, null=..., yesno=..., **kwargs) -> None: ...
    def render(self, value, record, bound_column):  # -> SafeString:
        ...
    def value(self, record, value, bound_column):  # -> str:
        ...
    @classmethod
    def from_field(cls, field, **kwargs):  # -> Self | None:
        ...
