"""
This type stub file was generated by pyright.
"""

from .base import Column, library

@library.register
class BooleanColumn(Column):
    """
    A column suitable for rendering boolean data.

    Arguments:
        null (bool): is `None` different from `False`?
        yesno (str): comma separated values string or 2-tuple to display for
                     True/False values.

    Rendered values are wrapped in a ``<span>`` to allow customization by using
    CSS. By default the span is given the class ``true``, ``false``.

    In addition to *attrs* keys supported by `~.Column`, the following are
    available:

     - ``span`` -- adds attributes to the ``<span>`` tag
    """
    def __init__(self, null=..., yesno=..., **kwargs) -> None:
        ...
    
    def render(self, value, record, bound_column): # -> SafeString:
        ...
    
    def value(self, record, value, bound_column): # -> str:
        """
        Returns the content for a specific cell similarly to `.render` however without any html content.
        """
        ...
    
    @classmethod
    def from_field(cls, field, **kwargs): # -> Self | None:
        ...
    


