from .base import Column, library

@library.register
class CheckBoxColumn(Column):
    def __init__(self, attrs=..., checked=..., **extra) -> None: ...
    @property
    def header(self):  # -> SafeString:
        ...
    def render(self, value, bound_column, record):  # -> SafeString:
        ...
    def is_checked(self, value, record):  # -> bool:
        ...
