"""
This type stub file was generated by pyright.
"""

from .base import library
from .templatecolumn import TemplateColumn

@library.register
class DateTimeColumn(TemplateColumn):
    """
    A column that renders `datetime` instances in the local timezone.

    Arguments:
        format (str): format string for datetime (optional).
                      Note that *format* uses Django's `date` template tag syntax.
        short (bool): if `format` is not specified, use Django's
                      ``SHORT_DATETIME_FORMAT``, else ``DATETIME_FORMAT``
    """
    def __init__(self, format=..., short=..., *args, **kwargs) -> None:
        ...
    
    @classmethod
    def from_field(cls, field, **kwargs): # -> Self | None:
        ...
    


