"""
This type stub file was generated by pyright.
"""

from .base import library
from .templatecolumn import TemplateColumn

@library.register
class DateColumn(TemplateColumn):
    """
    A column that renders dates in the local timezone.

    Arguments:
        format (str): format string in same format as Django's ``date`` template
                      filter (optional)
        short (bool): if `format` is not specified, use Django's
                      ``SHORT_DATE_FORMAT`` setting, otherwise use ``DATE_FORMAT``
    """
    def __init__(self, format=..., short=..., *args, **kwargs) -> None:
        ...
    
    @classmethod
    def from_field(cls, field, **kwargs): # -> Self | None:
        ...
    


