from .base import library
from .linkcolumn import BaseLinkColumn

@library.register
class FileColumn(BaseLinkColumn):
    def __init__(self, verify_exists=..., **kwargs) -> None: ...
    def get_url(self, value, record):  # -> Any | None:
        ...
    def text_value(self, record, value):  # -> object:
        ...
    def render(self, record, value):  # -> SafeString:
        ...
    @classmethod
    def from_field(cls, field, **kwargs):  # -> Self | None:
        ...
