from .base import Column, library

@library.register
class TemplateColumn(Column):
    empty_values = ...
    def __init__(
        self, template_code=..., template_name=..., extra_context=..., **extra
    ) -> None: ...
    def render(self, record, table, value, bound_column, **kwargs):  # -> SafeString:
        ...
    def value(self, **kwargs):  # -> str | None:
        ...
