"""
This type stub file was generated by pyright.
"""

from .base import library
from .templatecolumn import TemplateColumn

@library.register
class TimeColumn(TemplateColumn):
    """
    A column that renders times in the local timezone.

    Arguments:
        format (str): format string in same format as Django's ``time`` template filter (optional).
        short (bool): if *format* is not specified, use Django's ``TIME_FORMAT`` setting.
    """
    def __init__(self, format=..., *args, **kwargs) -> None:
        ...
    
    @classmethod
    def from_field(cls, field, **kwargs): # -> Self | None:
        ...
    


