from importlib.util import find_spec

from django import VERSION as DJANGO_VERSION

"""This module handles import compatibility issues."""
if find_spec("simplejson"): ...  # noqa: PYI002
else: ...
if find_spec("django"): ...  # noqa: PYI002
else:
    DJANGO_VERSION = ...
    class ImproperlyConfigured(Exception): ...  # noqa: N818

def choose_rediscache_driver():  # -> Literal['django_redis.cache.RedisCache', 'django.core.cache.backends.redis.RedisCache', 'redis_cache.RedisCache']:
    ...
def choose_postgres_driver():  # -> Literal['django.db.backends.postgresql_psycopg2', 'django.db.backends.postgresql']:
    ...
def choose_pymemcache_driver():  # -> LiteralString | Literal['django.core.cache.backends.memcached.PyLibMCCache']:
    ...

REDIS_DRIVER = ...
DJANGO_POSTGRES = ...
PYMEMCACHE_DRIVER = ...
