"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from os import PathLike
from typing import Any, Iterable, TypeVar, overload
from urllib.parse import ParseResult

"""
Django-environ allows you to utilize 12factor inspired environment
variables to configure your Django application.
"""
Openable = ...
logger = ...

class NoValue:
    """Represent of no value object."""
    def __repr__(self):  # -> str:
        ...

_CastT = TypeVar("_CastT", bound=type)
_CastIterT = TypeVar("_CastIterT", bound=type[Iterable[object]])
_AnyStr_co = TypeVar("_AnyStr_co", str, bytes, covariant=True)

class Env:
    """Provide scheme-based lookups of environment variables so that each
    caller doesn't have to pass in ``cast`` and ``default`` parameters.

    Usage:::

        import environ
        import os

        env = environ.Env(
            # set casting, default value
            MAIL_ENABLED=(bool, False),
            SMTP_LOGIN=(str, 'DEFAULT')
        )

        # Set the project base directory
        BASE_DIR = os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        )

        # Take environment variables from .env file
        environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

        # False if not in os.environ due to casting above
        MAIL_ENABLED = env('MAIL_ENABLED')

        # 'DEFAULT' if not in os.environ due to casting above
        SMTP_LOGIN = env('SMTP_LOGIN')
    """

    ENVIRON = ...
    NOTSET = ...
    BOOLEAN_TRUE_STRINGS = ...
    URL_CLASS = ParseResult
    POSTGRES_FAMILY = ...
    DEFAULT_DATABASE_ENV = ...
    DB_SCHEMES = ...
    _DB_BASE_OPTIONS = ...
    DEFAULT_CACHE_ENV = ...
    CACHE_SCHEMES = ...
    _CACHE_BASE_OPTIONS = ...
    DEFAULT_EMAIL_ENV = ...
    EMAIL_SCHEMES = ...
    _EMAIL_BASE_OPTIONS = ...
    DEFAULT_SEARCH_ENV = ...
    SEARCH_SCHEMES = ...
    ELASTICSEARCH_FAMILY = ...
    CLOUDSQL = ...
    def __init__(self, **scheme) -> None: ...
    def __call__(
        self,
        var: str,
        cast: Callable[..., _CastT] | None = ...,
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT | bytes | str | NoValue | None: ...
    def __contains__(self, var):  # -> bool:
        ...
    def str(
        self, var: str, default: str | None = ..., multiline: bool = False
    ) -> str: ...
    def bytes(self, var, default=..., encoding=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: bytes
        """
        ...

    def bool(self, var: str, default: bool | None = ...) -> bool: ...
    def int(self, var, default=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: int
        """
        ...

    def float(self, var, default=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: float
        """
        ...

    def json(self, var, default=...):  # -> bytes | str | NoValue | None:
        """
        :returns: Json parsed
        """
        ...

    @overload
    def list(
        self, var: str, cast: None = None, default: object = ...
    ) -> list[object]: ...
    @overload
    def list(self, var: str, cast: _CastT, default: object = ...) -> _CastT: ...
    def list(
        self, var: str, cast: _CastT | None = None, default: object = ...
    ) -> _CastT | list[object]: ...
    def tuple(self, var, cast=..., default=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: tuple
        """
        ...

    def dict(self, var, cast=..., default=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: dict
        """
        ...

    def url(self, var, default=...):  # -> bytes | str | NoValue | None:
        """
        :rtype: urllib.parse.ParseResult
        """
        ...

    def db_url(
        self,
        var: str = ...,
        default: dict[str, Any] | None = ...,
        engine: str | None = ...,
    ) -> dict[str, Any]: ...

    db: Callable[..., dict[str, Any]] = ...
    def cache_url(
        self, var=..., default=..., backend=...
    ):  # -> dict[Any, Any] | dict[str, str | Any | list[str]]:
        """Returns a config dictionary, defaulting to CACHE_URL.

        The cache method is an alias for cache_url.

        :rtype: dict
        """
        ...

    cache = ...
    def email_url(self, var=..., default=..., backend=...):  # -> dict[Any, Any]:
        """Returns a config dictionary, defaulting to EMAIL_URL.

        The email method is an alias for email_url.

        :rtype: dict
        """
        ...

    email = ...
    def search_url(self, var=..., default=..., engine=...):  # -> dict[Any, Any]:
        """Returns a config dictionary, defaulting to SEARCH_URL.

        :rtype: dict
        """
        ...

    def path(self, var, default=..., **kwargs):  # -> Path:
        """
        :rtype: Path
        """
        ...

    @overload
    def get_value(
        self,
        var: str,
        cast: None = None,
        default: object = ...,
        parse_default: bool = False,
    ) -> bytes | str | NoValue | None: ...
    @overload
    def get_value(
        self,
        var: str,
        cast: Callable[..., _CastT],
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT: ...
    def get_value(
        self,
        var: str,
        cast: Callable[[object], _CastT] | None = ...,
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT | bytes | str | NoValue | None: ...
    @classmethod
    def parse_value(cls, value, cast):
        """Parse and cast provided value

        :param value: Stringed value.
        :param cast: Type to cast return value as.

        :returns: Casted value
        """
        ...

    @classmethod
    def db_url_config(cls, url, engine=...):
        """Parse an arbitrary database URL.

        Supports the following URL schemas:

        * PostgreSQL: ``postgres[ql]?://`` or ``p[g]?sql://``
        * PostGIS: ``postgis://``
        * MySQL: ``mysql://`` or ``mysql2://``
        * MySQL (GIS): ``mysqlgis://``
        * MySQL Connector Python from Oracle: ``mysql-connector://``
        * SQLite: ``sqlite://``
        * SQLite with SpatiaLite for GeoDjango: ``spatialite://``
        * Oracle: ``oracle://``
        * Microsoft SQL Server: ``mssql://``
        * PyODBC: ``pyodbc://``
        * Amazon Redshift: ``redshift://``
        * LDAP: ``ldap://``

        :param urllib.parse.ParseResult or str url:
            Database URL to parse.
        :param str or None engine:
            If None, the database engine is evaluates from the ``url``.
        :return: Parsed database URL.
        :rtype: dict
        """
        ...

    @classmethod
    def cache_url_config(
        cls, url, backend=...
    ):  # -> dict[Any, Any] | dict[str, str | Any | list[str]]:
        """Parse an arbitrary cache URL.

        :param urllib.parse.ParseResult or str url:
            Cache URL to parse.
        :param str or None backend:
            If None, the backend is evaluates from the ``url``.
        :return: Parsed cache URL.
        :rtype: dict
        """
        ...

    @classmethod
    def email_url_config(cls, url, backend=...):  # -> dict[Any, Any]:
        """Parse an arbitrary email URL.

        :param urllib.parse.ParseResult or str url:
            Email URL to parse.
        :param str or None backend:
            If None, the backend is evaluates from the ``url``.
        :return: Parsed email URL.
        :rtype: dict
        """
        ...

    @classmethod
    def search_url_config(cls, url, engine=...):  # -> dict[Any, Any]:
        """Parse an arbitrary search URL.

        :param urllib.parse.ParseResult or str url:
            Search URL to parse.
        :param str or None engine:
            If None, the engine is evaluates from the ``url``.
        :return: Parsed search URL.
        :rtype: dict
        """
        ...

    @classmethod
    def read_env(
        cls,
        env_file: str | PathLike[_AnyStr_co] = ...,
        overwrite: bool = False,
        encoding: str = "utf8",
        **overrides: Any,
    ) -> None: ...

class FileAwareEnv(Env):
    """
    First look for environment variables with ``_FILE`` appended. If found,
    their contents will be read from the file system and used instead.

    Use as a drop-in replacement for the standard ``environ.Env``:

    .. code-block:: python

        python env = environ.FileAwareEnv()

    For example, if a ``SECRET_KEY_FILE`` environment variable was set,
    ``env("SECRET_KEY")`` would find the related variable, returning the file
    contents rather than ever looking up a ``SECRET_KEY`` environment variable.
    """

    ENVIRON = ...

class Path:
    """Inspired to Django Two-scoops, handling File Paths in Settings."""
    def path(self, *paths, **kwargs):  # -> Self:
        """Create new Path based on self.root and provided paths.

        :param paths: List of sub paths
        :param kwargs: required=False
        :rtype: Path
        """
        ...

    def file(self, name, *args, **kwargs):
        r"""Open a file.

        :param str name: Filename appended to :py:attr:`~root`
        :param \*args: ``*args`` passed to :py:func:`open`
        :param \**kwargs: ``**kwargs`` passed to :py:func:`open`
        :rtype: typing.IO[typing.Any]
        """
        ...

    @property
    def root(self):
        """Current directory for this Path"""
        ...

    def __init__(self, start=..., *paths, **kwargs) -> None: ...
    def __call__(self, *paths, **kwargs):
        """Retrieve the absolute path, with appended paths

        :param paths: List of sub path of self.root
        :param kwargs: required=False
        """
        ...

    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __add__(self, other):  # -> Path:
        ...
    def __sub__(self, other):  # -> Self | Path:
        ...
    def __invert__(self):  # -> Self:
        ...
    def __contains__(self, item): ...
    def __repr__(self):  # -> str:
        ...
    def __str__(self) -> str: ...
    def __unicode__(self): ...
    def __getitem__(self, *args, **kwargs): ...
    def __fspath__(self): ...
    def rfind(self, *args, **kwargs):  # -> int:
        """Proxy method to :py:func:`str.rfind`"""
        ...

    def find(self, *args, **kwargs):  # -> int:
        """Proxy method to :py:func:`str.find`"""
        ...
