from collections.abc import Callable
from os import PathLike
from typing import Any, TypeVar, overload
from urllib.parse import ParseResult

"""
Django-environ allows you to utilize 12factor inspired environment
variables to configure your Django application.
"""
Openable = ...
logger = ...

class NoValue:
    def __repr__(self):  # -> str:
        ...

_CastT = TypeVar("_CastT", bound=type)
_AnyStr_co = TypeVar("_AnyStr_co", str, bytes, covariant=True)

class Env:
    ENVIRON = ...
    NOTSET = ...
    BOOLEAN_TRUE_STRINGS = ...
    URL_CLASS = ParseResult
    POSTGRES_FAMILY = ...
    DEFAULT_DATABASE_ENV = ...
    DB_SCHEMES = ...
    _DB_BASE_OPTIONS = ...
    DEFAULT_CACHE_ENV = ...
    CACHE_SCHEMES = ...
    _CACHE_BASE_OPTIONS = ...
    DEFAULT_EMAIL_ENV = ...
    EMAIL_SCHEMES = ...
    _EMAIL_BASE_OPTIONS = ...
    DEFAULT_SEARCH_ENV = ...
    SEARCH_SCHEMES = ...
    ELASTICSEARCH_FAMILY = ...
    CLOUDSQL = ...
    def __init__(self, **scheme) -> None: ...
    def __call__(
        self,
        var: str,
        cast: Callable[..., _CastT] | None = ...,
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT | bytes | str | NoValue | None: ...
    def __contains__(self, var):  # -> bool:
        ...
    def str(
        self, var: str, default: str | None = ..., multiline: bool = False
    ) -> str: ...
    def bytes(self, var, default=..., encoding=...):  # -> bytes | str | NoValue | None:
        ...
    def bool(self, var: str, default: bool | None = ...) -> bool: ...
    def int(self, var, default=...):  # -> bytes | str | NoValue | None:
        ...
    def float(self, var, default=...):  # -> bytes | str | NoValue | None:
        ...
    def json(self, var, default=...):  # -> bytes | str | NoValue | None:
        ...
    @overload
    def list(
        self, var: str, cast: None = None, default: object = ...
    ) -> list[object]: ...
    @overload
    def list(self, var: str, cast: _CastT, default: object = ...) -> _CastT: ...
    def list(
        self, var: str, cast: _CastT | None = None, default: object = ...
    ) -> _CastT | list[object]: ...
    def tuple(self, var, cast=..., default=...):  # -> bytes | str | NoValue | None:
        ...
    def dict(self, var, cast=..., default=...):  # -> bytes | str | NoValue | None:
        ...
    def url(self, var, default=...):  # -> bytes | str | NoValue | None:
        ...
    def db_url(
        self,
        var: str = ...,
        default: dict[str, Any] | None = ...,
        engine: str | None = ...,
    ) -> dict[str, Any]: ...

    db: Callable[..., dict[str, Any]] = ...
    def cache_url(
        self, var=..., default=..., backend=...
    ) -> dict[Any, Any] | dict[str, str | Any | list[str]]: ...

    cache = ...
    def email_url(self, var=..., default=..., backend=...):  # -> dict[Any, Any]:
        ...

    email = ...
    def search_url(self, var=..., default=..., engine=...):  # -> dict[Any, Any]:
        ...
    def path(self, var, default=..., **kwargs):  # -> Path:
        ...
    @overload
    def get_value(
        self,
        var: str,
        cast: None = None,
        default: object = ...,
        parse_default: bool = False,
    ) -> bytes | str | NoValue | None: ...
    @overload
    def get_value(
        self,
        var: str,
        cast: Callable[..., _CastT],
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT: ...
    def get_value(
        self,
        var: str,
        cast: Callable[[object], _CastT] | None = ...,
        default: object = ...,
        parse_default: bool = False,
    ) -> _CastT | bytes | str | NoValue | None: ...
    @classmethod
    def parse_value(cls, value, cast): ...
    @classmethod
    def db_url_config(cls, url, engine=...): ...
    @classmethod
    def cache_url_config(
        cls, url, backend=...
    ):  # -> dict[Any, Any] | dict[str, str | Any | list[str]]:
        ...
    @classmethod
    def email_url_config(cls, url, backend=...):  # -> dict[Any, Any]:
        ...
    @classmethod
    def search_url_config(cls, url, engine=...):  # -> dict[Any, Any]:
        ...
    @classmethod
    def read_env(
        cls,
        env_file: str | PathLike[_AnyStr_co] = ...,
        overwrite: bool = False,
        encoding: str = "utf8",
        **overrides: Any,
    ) -> None: ...

class FileAwareEnv(Env):
    ENVIRON = ...

class Path:
    def path(self, *paths, **kwargs):  # -> Self:
        ...
    def file(self, name, *args, **kwargs): ...
    @property
    def root(self): ...
    def __init__(self, start=..., *paths, **kwargs) -> None: ...
    def __call__(self, *paths, **kwargs): ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __add__(self, other):  # -> Path:
        ...
    def __sub__(self, other):  # -> Self | Path:
        ...
    def __invert__(self):  # -> Self:
        ...
    def __contains__(self, item): ...
    def __repr__(self):  # -> str:
        ...
    def __unicode__(self): ...
    def __getitem__(self, *args, **kwargs): ...
    def __fspath__(self): ...
    def rfind(self, *args, **kwargs):  # -> int:
        ...
    def find(self, *args, **kwargs):  # -> int:
        ...
