from collections.abc import MutableMapping

"""Docker-style file variable support module."""

class FileAwareMapping(MutableMapping):
    def __init__(self, env=..., cache=...) -> None: ...
    def __getitem__(self, key):  # -> str:
        ...
    def __iter__(self):  # -> Generator[Any | str, Any, None]:
        ...
    def __len__(self):  # -> int:
        ...
    def __setitem__(self, key, value):  # -> None:
        ...
    def __delitem__(self, key):  # -> None:
        ...
