from . import filterset

class DjangoFilterBackend:
    filterset_base = filterset.FilterSet
    raise_exception = ...
    @property
    def template(
        self,
    ):  # -> Literal['django_filters/rest_framework/crispy_form.html', 'django_filters/rest_framework/form.html']:
        ...
    def get_filterset(self, request, queryset, view):  # -> AutoFilterSet | Any | None:
        ...
    def get_filterset_class(
        self, view, queryset=...
    ):  # -> Any | type[AutoFilterSet] | None:
        ...
    def get_filterset_kwargs(self, request, queryset, view):  # -> dict[str, Any]:
        ...
    def filter_queryset(self, request, queryset, view):  # -> QuerySet[Any] | Any:
        ...
    def to_html(self, request, queryset, view):  # -> SafeText | str | None:
        ...
