# Generated by Django 5.0.4 on 2024-04-23 05:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import djmoney.models.fields
import incredible_data.budget.budget_custom_fields
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='slug')),
                ('verified', models.BooleanField(default=False, help_text='checked by a human', verbose_name='verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])], verbose_name='receipt file')),
                ('analyze_result', models.JSONField(editable=False)),
                ('analyzed_datetime', models.DateTimeField(editable=False, verbose_name='analyzed at')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='alias')),
                ('matched_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.merchant', verbose_name='matched merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('merchant_confidence', incredible_data.budget.budget_custom_fields.SimplePercentageField(decimal_places=4, max_digits=10, verbose_name='merchant confidence')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='transaction date')),
                ('transaction_date_confidence', incredible_data.budget.budget_custom_fields.SimplePercentageField(decimal_places=4, max_digits=10, verbose_name='date confidence')),
                ('grand_total_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('grand_total', djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='grand total')),
                ('tax_rate', incredible_data.budget.budget_custom_fields.SimplePercentageField(decimal_places=5, default=0.089, help_text='if applicable', max_digits=15, verbose_name='tax rate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.merchant', verbose_name='merchant')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
