# Generated by Django 5.0.4 on 2024-04-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_receiptfile_analyze_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptfile',
            name='analyzed_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name='analyzed at'),
        ),
    ]
