# Generated by Django 5.0.4 on 2024-04-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_receiptfile_analyzed_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.receiptfile', verbose_name='linked receipt'),
        ),
    ]
