# Generated by Django 5.0.4 on 2024-04-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_receipt_receipt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='created',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='modified_by',
        ),
    ]
