# Generated by Django 5.0.4 on 2024-04-23 08:35

import incredible_data.budget.budget_custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_receipt_created_remove_receipt_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='grand_total_confidence',
            field=incredible_data.budget.budget_custom_fields.SimplePercentageField(decimal_places=4, default=0, max_digits=10, verbose_name='grand total confidence'),
            preserve_default=False,
        ),
    ]
