# Generated by Django 5.0.4 on 2024-04-23 08:36

import django.db.models.deletion
import django_extensions.db.fields
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_receipt_grand_total_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='product code or UPC')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0'), max_digits=19, verbose_name='total price')),
                ('parent_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.receipt', verbose_name='parent receipt')),
            ],
        ),
    ]
