# Generated by Django 5.0.4 on 2024-04-23 09:30

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_receiptitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='uuid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
