# Generated by Django 5.0.4 on 2024-04-24 19:28

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models
from django.apps.registry import Apps

DEFAULT_EXPENSE_CATEGORIES = [
    "Clothing",
    "Groceries",
    "Household",
    "(other)",
]

def add_default_categories(apps: Apps, schema_editor):
    ExpenseCategory = apps.get_model("budget", "ExpenseCategory")

    for category in DEFAULT_EXPENSE_CATEGORIES:
        ExpenseCategory.objects.create(name=category)

def remove_default_categories(apps: Apps, schema_editor):
    ExpenseCategory = apps.get_model("budget", "ExpenseCategory")

    for category in DEFAULT_EXPENSE_CATEGORIES:
        ExpenseCategory.objects.filter(name=category).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_receiptitem_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_default_categories, remove_default_categories),
        migrations.AddField(
            model_name='receiptitem',
            name='taxable',
            field=models.BooleanField(default=False, verbose_name='taxable'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.expensecategory', verbose_name='expense category'),
        ),
    ]
