# Generated by Django 5.0.4 on 2024-05-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_expensecategory_receiptitem_taxable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'expense categories'},
        ),
    ]
