# Generated by Django 5.0.6 on 2024-06-12 21:33

import django_rubble.fields.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='grand_total_confidence',
            field=django_rubble.fields.db_fields.SimplePercentageField(decimal_places=4, max_digits=10, verbose_name='grand total confidence'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='merchant_confidence',
            field=django_rubble.fields.db_fields.SimplePercentageField(decimal_places=4, max_digits=10, verbose_name='merchant confidence'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax_rate',
            field=django_rubble.fields.db_fields.SimplePercentageField(decimal_places=5, default=0.089, help_text='if applicable', max_digits=15, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction_date_confidence',
            field=django_rubble.fields.db_fields.SimplePercentageField(decimal_places=4, max_digits=10, verbose_name='date confidence'),
        ),
    ]
