from functools import lru_cache

@lru_cache
def uni_formset_template(template_pack=...):  # -> _EngineTemplate:
    ...
@lru_cache
def uni_form_template(template_pack=...):  # -> _EngineTemplate:
    ...

register = ...

@register.filter(name="crispy")
def as_crispy_form(
    form, template_pack=..., label_class=..., field_class=...
):  # -> SafeString:
    ...
@register.filter(name="as_crispy_errors")
def as_crispy_errors(form, template_pack=...):  # -> SafeString:
    ...
@register.filter(name="as_crispy_field")
def as_crispy_field(
    field, template_pack=..., label_class=..., field_class=...
):  # -> SafeString:
    ...
@register.filter(name="flatatt")
def flatatt_filter(attrs):  # -> SafeString:
    ...
@register.filter
def optgroups(field): ...
