# Generated by Django 5.0.4 on 2024-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_created_by_alter_contact_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('document', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('padding_digits', models.IntegerField(blank=True, null=True)),
                ('next_counter', models.IntegerField(default=1)),
                ('last_number', models.CharField(editable=False, max_length=50)),
                ('last_generated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
