# Generated by Django 5.0.6 on 2024-06-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_documentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnumber',
            name='padding_digits',
            field=models.IntegerField(default=0),
        ),
    ]
