# Generated by Django 5.2.2 on 2025-06-12 18:30

import django.db.models.deletion
import incredible_data.helpers.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the mood was recorded.",
                    ),
                ),
                ("anxiety", incredible_data.helpers.fields.RatingField()),
                ("energy", incredible_data.helpers.fields.RatingField()),
                ("notes", models.TextField(blank=True, help_text="Optional notes.")),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
