# Generated by Django 5.2.2 on 2025-08-11 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('is_score', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mood',
            name='anxiety',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='energy',
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.PositiveSmallIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mood.entry')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mood.metrictype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'metric_type'), name='unique_entry_metric')],
            },
        ),
    ]
