# Generated by Django 5.2.2 on 2025-08-11 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_metrictype_remove_mood_anxiety_remove_mood_energy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='effective_date',
            field=models.DateField(default=datetime.date.today, help_text='The date this entry is effective for.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes.'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='Indicates if a higher score is better (True) or a lower score is better (False).'),
        ),
    ]
