# Generated by Django 5.2.2 on 2025-08-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0003_alter_entry_options_entry_effective_date_entry_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_of_day',
            field=models.IntegerField(blank=True, choices=[(None, 'Unspecified'), (1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=None, null=True),
        ),
    ]
