# Generated by Django 5.2.2 on 2025-08-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_entry_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='max_value',
            field=models.IntegerField(default=10, help_text='Maximum allowed value for this metric type.'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='min_value',
            field=models.IntegerField(default=0, help_text='Minimum allowed value for this metric type.'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='scale_definition',
            field=models.TextField(blank=True, default='', help_text='Optional scale definition (e.g., JSON or description).'),
        ),
    ]
