# Generated by Django 5.2.5 on 2025-08-19 23:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0005_metrictype_max_value_metrictype_min_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='graph_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
