# Generated by Django 5.2.5 on 2025-09-12 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_metrictype_graph_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='metrics',
            field=models.ManyToManyField(through='mood.Metric', to='mood.metrictype'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='active_for',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
