from django.utils.functional import cached_property

class TableData:
    def __init__(self, data) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def set_table(self, table):  # -> None:
        ...
    @property
    def model(self):  # -> Any | None:
        ...
    @property
    def ordering(self):  # -> None:
        ...
    @property
    def verbose_name(self):  # -> Literal['item']:
        ...
    @property
    def verbose_name_plural(self):  # -> Literal['items']:
        ...
    @staticmethod
    def from_data(data):  # -> TableData | TableQuerysetData | TableListData:
        ...

class TableListData(TableData):
    @staticmethod
    def validate(data):  # -> bool:
        ...
    def __len__(self):  # -> int:
        ...
    @property
    def verbose_name(self):  # -> Any | str:
        ...
    @property
    def verbose_name_plural(self):  # -> Any | str:
        ...
    def order_by(self, aliases):  # -> None:
        ...

class TableQuerysetData(TableData):
    @staticmethod
    def validate(data):  # -> TypeIs[Callable[..., object]] | Literal[False]:
        ...
    def __len__(self):  # -> int:
        ...
    def set_table(self, table):  # -> None:
        ...
    @property
    def ordering(self):  # -> tuple[Any | OrderBy, ...] | None:
        ...
    def order_by(self, aliases):  # -> None:
        ...
    @cached_property
    def verbose_name(self): ...
    @cached_property
    def verbose_name_plural(self): ...
