from django.core.paginator import Paginator

class LazyPaginator(Paginator):
    look_ahead = ...
    def __init__(self, object_list, per_page, look_ahead=..., **kwargs) -> None: ...
    def validate_number(self, number):  # -> int:
        ...
    def page(self, number):  # -> Page[Any]:
        ...
    def is_last_page(self, number): ...

    count = ...
    num_pages = ...
    page_range = ...
