class CellAccessor:
    def __init__(self, row) -> None: ...
    def __getitem__(self, key): ...
    def __getattr__(self, name): ...

class BoundRow:
    def __init__(self, record, table) -> None: ...
    @property
    def table(self):  # -> Any:
        ...
    def get_even_odd_css_class(self):  # -> Literal['odd', 'even']:
        ...
    @property
    def attrs(self):  # -> AttributeDict:
        ...
    @property
    def record(self):  # -> Any:
        ...
    def __iter__(self):  # -> Generator[Any, Any, None]:
        ...
    def get_cell(self, name): ...
    def get_cell_value(self, name): ...
    def __contains__(self, item):  # -> bool:
        ...
    def items(self):  # -> Generator[tuple[Any, Any], Any, None]:
        ...

class BoundPinnedRow(BoundRow):
    @property
    def attrs(self):  # -> AttributeDict:
        ...

class BoundRows:
    def __init__(self, data, table, pinned_data=...) -> None: ...
    def generator_pinned_row(self, data):  # -> Generator[BoundPinnedRow, Any, None]:
        ...
    def __iter__(self):  # -> Generator[BoundPinnedRow | BoundRow, Any, None]:
        ...
    def __len__(self):  # -> int:
        ...
    def __getitem__(self, key):  # -> BoundRows | BoundRow:
        ...
