class DeclarativeColumnsMetaclass(type):
    def __new__(mcs, name, bases, attrs):  # -> Self:
        ...

class TableOptions:
    def __init__(self, options, class_name) -> None: ...

class Table(metaclass=DeclarativeColumnsMetaclass):
    def __init__(
        self,
        data=...,
        order_by=...,
        orderable=...,
        empty_text=...,
        exclude=...,
        attrs=...,
        row_attrs=...,
        pinned_row_attrs=...,
        sequence=...,
        prefix=...,
        order_by_field=...,
        page_field=...,
        per_page_field=...,
        template_name=...,
        default=...,
        request=...,
        show_header=...,
        show_footer=...,
        extra_columns=...,
    ) -> None: ...
    def get_top_pinned_data(self):  # -> None:
        ...
    def get_bottom_pinned_data(self):  # -> None:
        ...
    def before_render(self, request):  # -> None:
        ...
    def as_html(self, request):  # -> SafeString:
        ...
    def as_values(self, exclude_columns=...):  # -> Generator[list[Any], Any, None]:
        ...
    def has_footer(self):  # -> bool:
        ...
    @property
    def show_header(self): ...
    @show_header.setter
    def show_header(self, value):  # -> None:
        ...
    @property
    def order_by(self):  # -> OrderByTuple | None:
        ...
    @order_by.setter
    def order_by(self, value):  # -> None:
        ...
    @property
    def order_by_field(self): ...
    @order_by_field.setter
    def order_by_field(self, value):  # -> None:
        ...
    @property
    def page_field(self): ...
    @page_field.setter
    def page_field(self, value):  # -> None:
        ...
    def paginate(
        self, paginator_class=..., per_page=..., page=..., *args, **kwargs
    ):  # -> Self:
        ...
    @property
    def per_page_field(self): ...
    @per_page_field.setter
    def per_page_field(self, value):  # -> None:
        ...
    @property
    def prefix(self): ...
    @prefix.setter
    def prefix(self, value):  # -> None:
        ...
    @property
    def prefixed_order_by_field(self):  # -> str:
        ...
    @property
    def prefixed_page_field(self):  # -> str:
        ...
    @property
    def prefixed_per_page_field(self):  # -> str:
        ...
    @property
    def sequence(self):  # -> Sequence:
        ...
    @sequence.setter
    def sequence(self, value):  # -> None:
        ...
    @property
    def orderable(self): ...
    @orderable.setter
    def orderable(self, value):  # -> None:
        ...
    @property
    def template_name(self): ...
    @template_name.setter
    def template_name(self, value):  # -> None:
        ...
    @property
    def paginated_rows(self):  # -> _SupportsPagination[Any] | BoundRows:
        ...
    def get_column_class_names(self, classes_set, bound_column): ...

def table_factory(
    model, table=..., fields=..., exclude=..., localize=...
):  # -> type[Table]:
    ...
