from collections import OrderedDict

class Sequence(list):
    def expand(self, columns):  # -> Self:
        ...

class OrderBy(str):
    QUERYSET_SEPARATOR = ...
    def __new__(cls, value):  # -> Self:
        ...
    @property
    def bare(self):  # -> OrderBy | Self:
        ...
    @property
    def opposite(self):  # -> OrderBy:
        ...
    @property
    def is_descending(self):  # -> bool:
        ...
    @property
    def is_ascending(self):  # -> bool:
        ...
    def for_queryset(self):  # -> str:
        ...

class OrderByTuple(tuple):
    def __new__(cls, iterable):  # -> Self:
        ...
    def __contains__(self, name):  # -> bool:
        ...
    def __getitem__(self, index): ...
    @property
    def key(self):  # -> type[Comparator]:
        ...
    def get(self, key, fallback): ...
    @property
    def opposite(self):  # -> Self:
        ...

class Accessor(str):
    LEGACY_SEPARATOR = ...
    SEPARATOR = ...
    ALTERS_DATA_ERROR_FMT = ...
    LOOKUP_ERROR_FMT = ...
    def __init__(self, value, callable_args=..., callable_kwargs=...) -> None: ...
    def __new__(cls, value, callable_args=..., callable_kwargs=...):  # -> Self:
        ...
    def resolve(self, context, safe=..., quiet=...): ...
    @property
    def bits(self):  # -> tuple[()] | list[str]:
        ...
    def get_field(self, model):  # -> Any | None:
        ...
    def penultimate(self, context, quiet=...):  # -> tuple[Any, str]:
        ...

A = Accessor

class AttributeDict(OrderedDict):
    blacklist = ...
    def as_html(self):  # -> SafeString:
        ...

def segment(sequence, aliases):  # -> Generator[tuple[Any | OrderBy, ...], Any, None]:
    ...
def signature(fn):  # -> tuple[tuple[Any, ...], str | None]:
    ...
def call_with_appropriate(fn, kwargs):  # -> None:
    ...
def computed_values(d, kwargs=...):  # -> dict[Any, Any]:
    ...
