"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any, Optional

from django.db import models
from django.views.generic.list import ListView

from . import tables

class TableMixinBase:
    """
    Base mixin for the Single- and MultiTable class based views.
    """

    context_table_name = ...
    table_pagination = ...
    def get_context_table_name(self, table):  # -> str:
        """
        Get the name to use for the table's template variable.
        """
        ...

    def get_table_pagination(self, table):  # -> dict[Any, Any] | bool:
        """
        Return pagination options passed to `.RequestConfig`:
            - True for standard pagination (default),
            - False for no pagination,
            - a dictionary for custom pagination.

        `ListView`s pagination attributes are taken into account, if `table_pagination` does not
        define the corresponding value.

        Override this method to further customize pagination for a `View`.
        """
        ...

    def get_paginate_by(self, table_data) -> Optional[int]:
        """
        Determines the number of items per page, or ``None`` for no pagination.

        Args:
            table_data: The table's data.

        Returns:
            Optional[int]: Items per page or ``None`` for no pagination.
        """
        ...

class SingleTableMixin(TableMixinBase):
    table_class: type[tables.Table] | None = None
    table_data = ...
    def get_table_class(self):  # -> type[Table]:
        """
        Return the class to use for the table.
        """
        ...

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        ...

    def get_table_data(self):
        """
        Return the table data that should be used to populate the rows.
        """
        ...

    def get_table_kwargs(self):  # -> dict[Any, Any]:
        """
        Return the keyword arguments for instantiating the table.

        Allows passing customized arguments to the table constructor, for example,
        to remove the buttons column, you could define this method in your View::

            def get_table_kwargs(self):
                return {
                    'exclude': ('buttons', )
                }
        """
        ...

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """
        Overridden version of `.TemplateResponseMixin` to inject the table into
        the template's context.
        """
        ...

class SingleTableView(SingleTableMixin, ListView):
    model: type[models.Model] | None = None  # pyright: ignore[reportIncompatibleVariableOverride]

class MultiTableMixin(TableMixinBase):
    tables: Iterable[tables.Table] | None = None
    tables_data = ...
    table_prefix = ...
    context_table_name = ...
    def get_tables(self):  # -> list[Any]:
        """
        Return an array of table instances containing data.
        """
        ...

    def get_tables_data(self):  # -> None:
        """
        Return an array of table_data that should be used to populate each table
        """
        ...

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
