from collections.abc import Iterable
from typing import Any

from django.db import models
from django.views.generic.list import ListView

from . import tables

class TableMixinBase:
    context_table_name = ...
    table_pagination = ...
    def get_context_table_name(self, table):  # -> str:
        ...
    def get_table_pagination(self, table):  # -> dict[Any, Any] | bool:
        ...
    def get_paginate_by(self, table_data) -> int | None: ...

class SingleTableMixin(TableMixinBase):
    table_class: type[tables.Table] | None = None
    table_data = ...
    def get_table_class(self):  # -> type[Table]:
        ...
    def get_table(self, **kwargs): ...
    def get_table_data(self): ...
    def get_table_kwargs(self):  # -> dict[Any, Any]:
        ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class SingleTableView(SingleTableMixin, ListView):
    model: type[models.Model] | None = None

class MultiTableMixin(TableMixinBase):
    tables: Iterable[tables.Table] | None = None
    tables_data = ...
    table_prefix = ...
    context_table_name = ...
    def get_tables(self):  # -> list[Any]:
        ...
    def get_tables_data(self):  # -> None:
        ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
