name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-django-image:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: "./incredible_data"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and Push Django Image"
        run: |
            docker build . --file "compose/production/django/Dockerfile" --tag ghcr.io/woostertech/incredible_data_production_django:latest --tag ghcr.io/woostertech/incredible_data_production_celeryworker:latest
            docker push ghcr.io/woostertech/incredible_data_production_django:latest
            docker push ghcr.io/woostertech/incredible_data_production_celeryworker:latest

      - name: "Build and Push PostgreSQL Image"
        run: |
            docker build . --file "compose/production/postgres/Dockerfile" --tag ghcr.io/woostertech/incredible_data_production_postgres:latest
            docker push ghcr.io/woostertech/incredible_data_production_postgres:latest

      - name: "Build and Push Traefik Image"
        run: |
            docker build . --file "compose/production/traefik/Dockerfile" --tag ghcr.io/woostertech/incredible_data_production_traefik:latest
            docker push ghcr.io/woostertech/incredible_data_production_traefik:latest

      - name: "Build and Push nginx Image"
        run: |
            docker build . --file "compose/production/nginx/Dockerfile" --tag ghcr.io/woostertech/incredible_data_local_nginx:latest
            docker push ghcr.io/woostertech/incredible_data_local_nginx:latest

  push-postgres-image:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: "./incredible_data"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: |
            docker build . --file "compose/production/django/Dockerfile" --tag ghcr.io/woostertech/incredible_data_production_django:latest
            docker push ghcr.io/woostertech/incredible_data_production_django:latest
